submitting new copy manglemesa operation and adding fix to ADIOS and mxml
git-svn-id: svn+ssh://edison.nersc.gov/project/projectdirs/visit/svn/visit/trunk@14380 18c085ea-50e0-402c-830e-de6fd14e8384

diff --git a/src/svn_bin/build_visit b/src/svn_bin/build_visit
--- a/src/svn_bin/build_visit
+++ b/src/svn_bin/build_visit
@@ -1623,7 +1623,7 @@ export ADIOS_VERSION=${ADIOS_VERSION:-"1.2.1"}
 export ADIOS_COMPATIBILITY_VERSION=${ADIOS_COMPATIBILITY_VERSION:-"1.2.1"}
 export ADIOS_BUILD_DIR=${ADIOS_BUILD_DIR:-"adios-1.2.1"}
 
-export MXML_FILE=${ADIOS_FILE:-"mxml-2.6.tar.gz"}
+export MXML_FILE=${MXML_FILE:-"mxml-2.6.tar.gz"}
 export MXML_VERSION=${MXML_VERSION:-"2.6"}
 export MXML_COMPATIBILITY_VERSION=${MXML_COMPATIBILITY_VERSION:-"2.6"}
 export MXML_BUILD_DIR=${MXML_BUILD_DIR:-"mxml-2.6"}
@@ -2518,6 +2518,16 @@ function check_optional_3rdparty
             ANY_ERRORS="yes"
             DO_XDMF="no"
             error "Unable to build XDMF.  ${XDMF_FILE} not found."
+        fi
+    fi
+
+    if [[ "$DO_MXML" == "yes" ]] ; then
+        ensure_built_or_ready "MXML" $MXML_VERSION $MXML_BUILD_DIR $MXML_FILE
+            
+        if [[ $? != 0 ]] ; then
+            ANY_ERRORS="yes"
+            DO_MXML="no"
+            error "Unable to build MXML.  ${MXML_FILE} not found."
         fi
     fi
 
@@ -4375,21 +4385,16 @@ echo " $PYTHON_INSTALL ${PYTHON_INSTALL}/python"
     #
 
     if [[ "$DO_DBIO_ONLY" != "yes" ]]; then
-        cd MangleMesaInclude
-        export BAD_MESA="$PWD"
-        cd ..
-        mkdir "$VISITDIR/vtk/${VTK_VERSION}/$VISITARCH/include/MangleMesaInclude"
-        cp MangleMesaInclude/*.h  "$VISITDIR/vtk/${VTK_VERSION}/$VISITARCH/include/MangleMesaInclude"
-        cd "$VISITDIR/vtk/${VTK_VERSION}/$VISITARCH/include/MangleMesaInclude"
-        SED_STR1=$(echo "$BAD_MESA" | sed 's/\//\\\//g')  
-        # Converts all '/' to "\/" for later sed'ding 
-        SED_STR2=$(echo "$VISITDIR/vtk/${VTK_VERSION}/$VISITARCH/include/MangleMesaInclude" | sed 's/\//\\\//g')
-        for i in *.h ; do
-           cat $i | sed 's/'${SED_STR1}'/'${SED_STR2}'/g' > tmp.h
-           mv -f tmp.h $i
-        done
-        cd $BAD_MESA
-        cd ../
+         echo "Copying MangleMesaInclude directory"
+         mkdir -p VISIT_VTK_MANGLED_MESA_MOVE_DIR
+         cd VISIT_VTK_MANGLED_MESA_MOVE_DIR
+         /bin/echo -e "cmake_minimum_required(version 2.8)\nuse_mangled_mesa($VISITDIR/mesa/${MESA_VERSION}/${VISITARCH}/include/GL $VISITDIR/vtk/${VTK_VERSION}/$VISITARCH/include/MangleMesaInclude)\n" > CMakeLists.txt
+         #this will call cmake to copy the MesaGL to the VTK install directory
+         ${CMAKE_INSTALL}/cmake .
+         cd ../
+
+         #remove the tmp directory
+         rm -fR VISIT_VTK_MANGLED_MESA_MOVE_DIR
     fi
 
     if [[ "$DO_GROUP" == "yes" ]] ; then
@@ -9437,7 +9442,7 @@ for arg in "${arguments[@]}" ; do
     case $arg in
         --absolute) ABS_PATH="yes"; ON_ABS_PATH="on";;
         --all-io) DO_ALLIO="yes";;
-        --adios) DO_ADIOS="yes"; ON_ADIOS="on";;
+        --adios) DO_ADIOS="yes"; ON_ADIOS="on"; DO_MXML="yes"; ON_MXML="yes";;
         --advio) DO_ADVIO="yes"; ON_ADVIO="on";;
         --arch) next_arg="arch";;
         --boxlib) DO_BOXLIB="yes"; ON_BOXLIB="on";;
@@ -9597,6 +9602,8 @@ if [[ "$DO_DBIO_ONLY" == "yes" || "$DO_ALLIO" == "yes" ]]; then
     ON_XDMF="on"
     DO_ADIOS="yes"
     ON_ADIOS="on"
+    DO_MXML="yes"
+    ON_MXML="on"
 
     #
     # Releasibility of these libs is not yet understood
