Fixed so that setting THIRD_PARTY_PATH via gui actually works
git-svn-id: svn+ssh://edison.nersc.gov/project/projectdirs/visit/svn/visit/trunk@3587 18c085ea-50e0-402c-830e-de6fd14e8384

diff --git a/src/svn_bin/build_visit b/src/svn_bin/build_visit
--- a/src/svn_bin/build_visit
+++ b/src/svn_bin/build_visit
@@ -312,6 +312,10 @@
 #     Brad Whitlock, Wed Mar 12 11:15:09 PDT 2008
 #     Fixed Mesa build on AIX.
 #
+#     Kathleen Bonnell, Wed Mar 26 17:10:12 PDT 2008 
+#     Moved calls to check_more_options, check_parallel and check_variables
+#     to BEFORE THIRD_PARTY_PATH is used to set VISITDIR.
+#
 # *****************************************************************************
 #
 # *************************************************************************** #
@@ -6979,6 +6983,34 @@ if [[ -e "tmp$$" ]] ; then
     rm tmp$$
 fi
 
+#
+# See if the used needs to modify some variables
+#
+check_more_options
+if [[ $? != 0 ]] ; then
+   echo "Stopping build because of bad variable option setting error."
+   exit 1
+fi
+
+#
+# See if the user wants to build a parallel version.
+#
+check_parallel
+if [[ $? != 0 ]] ; then
+   echo "Stopping build because necessary parallel options are not set."
+   exit 1
+fi
+
+#
+# See if the user wants to modify variables
+#
+check_variables
+if [[ $? != 0 ]] ; then
+   echo "Stopping build because of bad variable option setting error."
+   exit 1
+fi
+
+
 if [[ $VISITARCH == "" ]] ; then
     export VISITARCH=${ARCH}_${C_COMPILER}
     if [[ "$CXX_COMPILER" == "g++" ]] ; then
@@ -7063,33 +7095,6 @@ if [[ "$DO_QT" == "yes" ]] ; then
          read RESPONSE
       done
    fi
-fi
-
-#
-# See if the used needs to modify some variables
-#
-check_more_options
-if [[ $? != 0 ]] ; then
-   echo "Stopping build because of bad variable option setting error."
-   exit 1
-fi
-
-#
-# See if the user wants to build a parallel version.
-#
-check_parallel
-if [[ $? != 0 ]] ; then
-   echo "Stopping build because necessary parallel options are not set."
-   exit 1
-fi
-
-#
-# See if the user wants to modify variables
-#
-check_variables
-if [[ $? != 0 ]] ; then
-   echo "Stopping build because of bad variable option setting error."
-   exit 1
 fi
 
 #
