minor fixes to _VERSION/_FILE/_BUILD_DIR symbols for some libs to make them easier to edit for version, correct and up to date
git-svn-id: svn+ssh://edison.nersc.gov/project/projectdirs/visit/svn/visit/trunk@7613 18c085ea-50e0-402c-830e-de6fd14e8384

diff --git a/src/svn_bin/build_visit b/src/svn_bin/build_visit
--- a/src/svn_bin/build_visit
+++ b/src/svn_bin/build_visit
@@ -640,6 +640,12 @@
 #
 #     Mark C. Miller, Mon Jun 22 13:56:05 PDT 2009
 #     Removed dup ON_SILO/DO_SILO lines.
+#
+#     Mark C. Miller, Mon Jun 22 21:54:25 PDT 2009
+#     Adjusted _VERSION/_FILE/_BUILD_DIR symbols for FastBit, H5Part, HDF5
+#     and Silo so that you don't have upteen different places to edit the
+#     version number, they are consistent with other lib symbols and they
+#     are correct and up to date.
 # *****************************************************************************
 #                                                                             #
 # *************************************************************************** #
@@ -950,10 +956,12 @@ export SZIP_VERSION=${SZIP_VERSION:-"2.1"}
 export SZIP_COMPATIBILITY_VERSION=${SZIP_COMPATIBILITY_VERSION:-"2.0"}
 export SZIP_BUILD_DIR=${SZIP_BUILD_DIR:-"szip-2.1"}
 
-export HDF5_FILE=${HDF5_FILE:-"hdf5-1.8.2.tar.gz"}
 export HDF5_VERSION=${HDF5_VERSION:-"1.8.2"}
+export HDF5_FILE=${HDF5_FILE:-"hdf5-${HDF5_VERSION}.tar.gz"}
 export HDF5_COMPATIBILITY_VERSION=${HDF5_COMPATIBILITY_VERSION:-"1.8"}
-export HDF5_BUILD_DIR=${HDF5_BUILD_DIR:-"hdf5-1.8.2"}
+export HDF5_BUILD_DIR=${HDF5_BUILD_DIR:-"hdf5-${HDF5_VERSION}"}
+# Note: Versions of HDF5 1.6.5 and earlier DO NOT have last path component
+export HDF5_URL=${HDF5_URL:-"http://www.hdfgroup.org/ftp/HDF5/prev-releases/hdf5-${HDF5_VERSION}/src"}
 
 export HDF4_FILE=${HDF4_FILE:-"HDF4.2r1.tar.gz"}
 export HDF4_VERSION=${HDF4_VERSION:-"4.2.1"}
@@ -995,25 +1003,27 @@ export CFITSIO_VERSION=${CFITSIO_VERSION:-"3006"}
 export CFITSIO_COMPATIBILITY_VERSION=${CFITSIO_COMPATIBILITY_VERSION:-"3.0"}
 export CFITSIO_BUILD_DIR=${CFITSIO_BUILD_DIR:-"cfitsio"}
 
-export H5PART_FILE=${H5PART_FILE-"H5Part-1.4.2.tar.gz"}
-export H5PART_VERSION=${H5PART_VERSION-"1.4.2"}
-export H5PART_COMPATIBILITY_VERSION=${H5PART_COMPATIBILITY_VERSION-"1.4"}
-export H5PART_BUILD_DIR=${H5PART_DIR-"H5Part-1.4.2"}
+export H5PART_VERSION=${H5PART_VERSION:-"1.4.2"}
+export H5PART_FILE=${H5PART_FILE:-"H5Part-${H5PART_VERSION}.tar.gz"}
+export H5PART_COMPATIBILITY_VERSION=${H5PART_COMPATIBILITY_VERSION:-"1.4"}
+export H5PART_BUILD_DIR=${H5PART_BUILD_DIR:-"H5Part-${H5PART_VERSION}"}
 
-export FASTBIT_URL=${FASTBIT_URL-"https://codeforge.lbl.gov/frs/download.php/62/fastbit-ibis1.0.9.tar.gz"}
-export FASTBIT_FILE=${FASTBIT_FILE-"fastbit-ibis1.0.9.tar.gz"}
-export FASTBIT_VERSION=${FASTBIT_VERSION-"1.0.9"}
-export FASTBIT_DIR=${FASTBIT_DIR-"fastbit-ibis1.0.9"}
+export FASTBIT_VERSION=${FASTBIT_VERSION:-"1.0.9"}
+export FASTBIT_FILE=${FASTBIT_FILE:-"fastbit-ibis${FASTBIT_VERSION}.tar.gz"}
+# Note: last 2-digit field in URL changes with version.
+export FASTBIT_URL=${FASTBIT_URL:-"https://codeforge.lbl.gov/frs/download.php/62"}
+export FASTBIT_BUILD_DIR=${FASTBIT_BUILD_DIR:-"fastbit-ibis1.0.9"}
 
 export CCMIO_FILE=${CCMIO_FILE:-"libccmio-2.6.1.tar.gz"}
 export CCMIO_VERSION=${CCMIO_VERSION:-"2.6.1"}
 export CCMIO_COMPATIBILITY_VERSION=${CCMIO_COMPATIBILITY_VERSION:-"2.0"}
 export CCMIO_BUILD_DIR=${CCMIO_BUILD_DIR:-"libccmio-2.6.1"}
 
-export SILO_FILE=${SILO_FILE:-"silo-4.7.tar.gz"}
 export SILO_VERSION=${SILO_VERSION:-"4.7"}
+export SILO_FILE=${SILO_FILE:-"silo-${SILO_VERSION}.tar.gz"}
 export SILO_COMPATIBILITY_VERSION=${SILO_COMPATIBILITY_VERSION:-"4.7"}
-export SILO_BUILD_DIR=${SILO_BUILD_DIR:-"silo-4.7"}
+export SILO_BUILD_DIR=${SILO_BUILD_DIR:-"silo-${SILO_VERSION}"}
+export SILO_URL=${SILO_URL:-https://wci.llnl.gov/codes/silo/silo-${SILO_VERSION}}
 
 export ITAPS_MOAB_FILE=${ITAPS_MOAB_FILE:-"ITAPS-MOAB-3.99-20Apr09.tar.gz"}
 export ITAPS_MOAB_VERSION=${ITAPS_MOAB_VERSION:-"3.99-20Apr09"}
@@ -1700,7 +1710,7 @@ function check_optional_3rdparty
     fi
 
     if [[ "$DO_FASTBIT" == "yes" ]] ; then
-        ensure_built_or_ready "fastbit" $FASTBIT_VERSION $FASTBIT_DIR $FASTBIT_FILE $FASTBIT_URL
+        ensure_built_or_ready "fastbit" $FASTBIT_VERSION $FASTBIT_BUILD_DIR $FASTBIT_FILE $FASTBIT_URL
         if [[ $? != 0 ]] ; then
             warn "Unable to build FastBit.  ${FASTBIT_FILE} not found."
             warn "FastBit is not available for download from the VisIt build site"
@@ -1747,7 +1757,7 @@ function check_optional_3rdparty
     fi
     
     if [[ "$DO_HDF5" == "yes" ]] ; then
-        ensure_built_or_ready "hdf5" $HDF5_VERSION $HDF5_BUILD_DIR $HDF5_FILE ftp://ftp.hdfgroup.org/HDF5/prev-releases/hdf5-1.8.2/src
+        ensure_built_or_ready "hdf5" $HDF5_VERSION $HDF5_BUILD_DIR $HDF5_FILE $HDF5_URL 
         if [[ $? != 0 ]] ; then
             ANY_ERRORS="yes"
             DO_HDF5="no"
@@ -1803,7 +1813,7 @@ function check_optional_3rdparty
     fi
     
     if [[ "$DO_SILO" == "yes" ]] ; then
-        ensure_built_or_ready "silo" $SILO_VERSION $SILO_BUILD_DIR $SILO_FILE "https://wci.llnl.gov/codes/silo/silo-4.7"
+        ensure_built_or_ready "silo" $SILO_VERSION $SILO_BUILD_DIR $SILO_FILE $SILO_URL
         if [[ $? != 0 ]] ; then
             ANY_ERRORS="yes"
             DO_SILO="no"
@@ -3948,17 +3958,18 @@ function build_silo
        WITHSILOQTARG="--disable-silex"
     fi
 
-    echo ./configure CXX="$CXX_COMPILER" CC="$C_COMPILER" \
-        CFLAGS="$C_OPT_FLAGS" CXXFLAGS="$CXX_OPT_FLAGS" \
-        --prefix="$VISITDIR/silo/$SILO_VERSION/$VISITARCH" \
-        "$WITHHDF5ARG" "$WITHSZIPARG" "$WITHSILOQTARG" \
-        --without-readline --disable-fortran
+    info ./configure CXX=\"$CXX_COMPILER\" CC=\"$C_COMPILER\" \
+        CFLAGS=\"$C_OPT_FLAGS\" CXXFLAGS=\"$CXX_OPT_FLAGS\" \
+        --prefix=\"$VISITDIR/silo/$SILO_VERSION/$VISITARCH\" \
+        \"$WITHHDF5ARG\" \"$WITHSZIPARG\" \"$WITHSILOQTARG\" \
+        --without-readline --disable-fortran"
 
     ./configure CXX="$CXX_COMPILER" CC="$C_COMPILER" \
         CFLAGS="$C_OPT_FLAGS" CXXFLAGS="$CXX_OPT_FLAGS" \
         --prefix="$VISITDIR/silo/$SILO_VERSION/$VISITARCH" \
         "$WITHHDF5ARG" "$WITHSZIPARG" "$WITHSILOQTARG" \
         --without-readline --disable-fortran
+
     if [[ $? != 0 ]] ; then
        warn "Silo configure failed.  Giving up"
        return 1
@@ -4068,11 +4079,15 @@ function build_szip
     info "Configuring SZIP . . ."
     cd ${SZIP_BUILD_DIR} || error "Can't cd to szip build dir."
     info "Invoking command to configure SZIP"
-    echo "Invoking command to configure SZIP: ./configure CXX=\"$CXX_COMPILER\" CC=\"$C_COMPILER\" LIBS=\"-lm\" CFLAGS=\"$C_OPT_FLAGS\" CXXFLAGS=\"$CXX_OPT_FLAGS\" --prefix=\"$VISITDIR/szip/$SZIP_VERSION/$VISITARCH\""
+
+    info "./configure CXX=\"$CXX_COMPILER\" CC=\"$C_COMPILER\" LIBS=\"-lm\" \
+        CFLAGS=\"$C_OPT_FLAGS\" CXXFLAGS=\"$CXX_OPT_FLAGS\" \
+        --prefix=\"$VISITDIR/szip/$SZIP_VERSION/$VISITARCH\""
 
     ./configure CXX="$CXX_COMPILER" CC="$C_COMPILER" LIBS="-lm" \
         CFLAGS="$C_OPT_FLAGS" CXXFLAGS="$CXX_OPT_FLAGS" \
         --prefix="$VISITDIR/szip/$SZIP_VERSION/$VISITARCH"
+
     if [[ $? != 0 ]] ; then
        warn "SZIP configure failed.  Giving up"
        return 1
@@ -4170,10 +4185,12 @@ function build_hdf5
         sz_dir="${VISITDIR}/szip/${SZIP_VERSION}/${VISITARCH}"
         cf_szip="--with-szlib=${sz_dir}"
     fi
-    echo ./configure CXX="$CXX_COMPILER" CC="$C_COMPILER" \
-        CFLAGS="$C_OPT_FLAGS" CXXFLAGS="$CXX_OPT_FLAGS" \
-        --prefix="$VISITDIR/hdf5/$HDF5_VERSION/$VISITARCH" \
-        ${cf_szip}
+
+    info "./configure CXX=\"$CXX_COMPILER\" CC=\"$C_COMPILER\" \
+        CFLAGS=\"$C_OPT_FLAGS\" CXXFLAGS=\"$CXX_OPT_FLAGS\" \
+        --prefix=\"$VISITDIR/hdf5/$HDF5_VERSION/$VISITARCH\" \
+        ${cf_szip}"
+
     ./configure CXX="$CXX_COMPILER" CC="$C_COMPILER" \
         CFLAGS="$C_OPT_FLAGS" CXXFLAGS="$CXX_OPT_FLAGS" \
         --prefix="$VISITDIR/hdf5/$HDF5_VERSION/$VISITARCH" \
@@ -7275,8 +7292,8 @@ function build_fastbit
     #
     # Unzip the file, provided a gzipped file exists.
     #
-    if [[ -d ${FASTBIT_DIR} ]] ; then
-       info_box "Found ${FASTBIT_DIR} . . ." 1>&3
+    if [[ -d ${FASTBIT_BUILD_DIR} ]] ; then
+       info_box "Found ${FASTBIT_BUILD_DIR} . . ." 1>&3
     elif [[ -f ${FASTBIT_FILE} ]] ; then
        info_box "Unzipping/Tarring ${FASTBIT_FILE} . . ." 1>&3
        uncompress_untar ${FASTBIT_FILE}
@@ -7297,7 +7314,7 @@ function build_fastbit
 
     #
     info_box "Configuring FastBit . . ." 1>&3
-    cd ${FASTBIT_DIR} || error "Can't cd to fastbit build dir."
+    cd ${FASTBIT_BUILD_DIR} || error "Can't cd to fastbit build dir."
     echo "Invoking command to configure FastBit"
     ./configure \
        CXX="$CXX_COMPILER" CC="$C_COMPILER" \
@@ -8136,7 +8153,7 @@ printvariables () {
 
   printf "%s%s\n" "FASTBIT_FILE=" "${FASTBIT_FILE}"
   printf "%s%s\n" "FASTBIT_VERSION=" "${FASTBIT_VERSION}"
-  printf "%s%s\n" "FASTBIT_DIR=" "${FASTBIT_DIR}"
+  printf "%s%s\n" "FASTBIT_BUILD_DIR=" "${FASTBIT_BUILD_DIR}"
 
   printf "%s%s\n" "CCMIO_FILE=" "${CCMIO_FILE}"
   printf "%s%s\n" "CCMIO_VERSION=" "${CCMIO_VERSION}"
@@ -8893,11 +8910,10 @@ if [[ $? != 0 ]] ; then
 fi
 
 
-cd "$START_DIR"
 #
 # We are now ready to build.  Start with Mesa.
 #
-
+cd "$START_DIR"
 if [[ "$DO_MESA" == "yes" ]] ; then
     check_if_installed "mesa" $MESA_VERSION
     if [[ $? == 0 ]] ; then
@@ -8935,7 +8951,6 @@ fi
 # Build CMake
 #
 cd "$START_DIR"
-
 if [[ "$DO_CMAKE" == "yes" ]]; then
     check_if_installed "cmake" $CMAKE_VERSION
     if [[ $? == 0 ]] ; then
