I modified build_visit to use anonymous svn checkout as a backup for downloading third party libraries. It tries anonymous svn after the directories specified in the script to download the file from and before it tries https from the visit web site. I also changed anonymous svn checkout to use https instead of http. This resolves #547.
git-svn-id: svn+ssh://edison.nersc.gov/project/projectdirs/visit/svn/visit/trunk@13471 18c085ea-50e0-402c-830e-de6fd14e8384

diff --git a/src/svn_bin/build_visit b/src/svn_bin/build_visit
--- a/src/svn_bin/build_visit
+++ b/src/svn_bin/build_visit
@@ -1048,6 +1048,10 @@
 #     Eric Brugger, Mon Jan 10 12:33:31 PST 2011
 #     I modified the script to build exodus 4.98 instead of exodus 4.46.
 #
+#     Eric Brugger, Mon Jan 10 16:00:13 PST 2011
+#     I modified the script to use https instead of http for anonymous svn
+#     checkouts.
+#
 # *****************************************************************************
 
 
@@ -1359,7 +1363,7 @@ if [[ "$CXX_COMPILER" == "g++" ]] ; then
 fi
 
 
-export SVN_ANON_ROOT_PATH="http://portal.nersc.gov/svn/visit"
+export SVN_ANON_ROOT_PATH="https://portal.nersc.gov/svn/visit"
 # Setup svn path: use SVN_NERSC_NAME if set
 if test -z "$SVN_NERSC_NAME" ; then
     export SVN_REPO_ROOT_PATH="svn+ssh://svn.nersc.gov/svn/visit"
@@ -1757,6 +1761,10 @@ function uncompress_untar
 #                                                                             #
 #   Mark C. Miller, Wed Feb  3 09:47:52 PST 2010                              #
 #   Made it fall back to anon svn checkout                                    #
+#                                                                             #
+#   Eric Brugger, Mon Jan 10 16:00:13 PST 2011                                #
+#   I made it always fall back to anonymous svn checkout.                     #
+#                                                                             #
 # *************************************************************************** #
 
 function download_file
@@ -1798,28 +1806,40 @@ function download_file
         rm -f $dfile
     fi
 
-    if [[ "$1" == "" ]] ; then
-        # If SVN was not requested or if it failed...
-        if [[ "$dfile" == "$VISIT_FILE" ]] ; then
-            try_download_file https://wci.llnl.gov/codes/visit/$VISIT_VERSION/$dfile $dfile
-        else
-            try_download_file https://wci.llnl.gov/codes/visit/3rd_party/$dfile $dfile
-        fi
-
+    # If the visit source code is requested try that next.
+    if [[ "$dfile" == "$VISIT_FILE" ]] ; then
+        try_download_file https://wci.llnl.gov/codes/visit/$VISIT_VERSION/$dfile $dfile
         if [[ $? == 0 ]] ; then
             return 0
         fi
     fi
 
-    # Ok, if any of above had succeeded, they would have returned early.
-    # So, now try various places listed.
-    # try all sites listed incl. falling back to visit's 3rd_party
-    for site in $* https://wci.llnl.gov/codes/visit/3rd_party; do
-        try_download_file $site/$dfile $dfile
+    # Now try the various places listed.
+    if [[ "$1" != "" ]] ; then
+        for site in $* ; do
+            try_download_file $site/$dfile $dfile
+            if [[ $? == 0 ]] ; then
+                return 0
+            fi
+        done
+    fi
+
+    # Now try anonymous svn unless we tried it above.
+    if [[ "$DO_SVN" != "yes" && "$DO_ANON_SVN" != "yes" ]] ; then
+        svn cat $SVN_ANON_ROOT_PATH/trunk/third_party/$dfile > $dfile
+        if [[ $? == 0 && -e $dfile ]] ; then
+            info "Anonymous SVN download succeeded: $SVN_ANON_ROOT_PATH/trunk/third_party/$dfile"
+            return 0
+        fi
+        warn "Anonymous SVN download attempt failed: $SVN_ANON_ROOT_PATH/trunk/third_party/$dfile"
+        rm -f $dfile
+    fi
+
+    # Now try visit's 3rd_party.
+    try_download_file https://wci.llnl.gov/codes/visit/3rd_party/$dfile $dfile
     if [[ $? == 0 ]] ; then
         return 0
     fi
-    done
     info "Failed to download $dfile"
     return 1
 }
