Merge 1.12RC to trunk: update NetCDF version.
git-svn-id: svn+ssh://edison.nersc.gov/project/projectdirs/visit/svn/visit/trunk@7344 18c085ea-50e0-402c-830e-de6fd14e8384

diff --git a/src/svn_bin/build_visit b/src/svn_bin/build_visit
--- a/src/svn_bin/build_visit
+++ b/src/svn_bin/build_visit
@@ -620,6 +620,10 @@
 #     left as 1.8.1 or 1.6.5.  I updated *all* references to be to 1.8.2.
 #     At the very least, this fixed ftp downloading of HDF5.
 #
+#     Tom Fogal, Sat May 16 14:47:05 MDT 2009
+#     Enhanced downloadv to check subversion.
+#     Update NetCDF version to workaround compilation issues.
+#
 # *****************************************************************************
 #
 # *************************************************************************** #
@@ -937,10 +941,10 @@ export MILI_VERSION=${MILI_VERSION:-"1.10.0"}
 export MILI_COMPATIBILITY_VERSION=${MILI_COMPATIBILITY_VERSION:-"1.0"}
 export MILI_BUILD_DIR=${MILI_BUILD_DIR:-"mili"}
 
-export NETCDF_FILE=${NETCDF_FILE:-"netcdf.tar.gz"}
-export NETCDF_VERSION=${NETCDF_VERSION:-"3.6.0"}
-export NETCDF_COMPATIBILITY_VERSION=${NETCDF_COMPATIBILITY_VERSION:-"3.6"}
-export NETCDF_BUILD_DIR=${NETCDF_BUILD_DIR:-"netcdf-3.6.0-p1/src"}
+export NETCDF_VERSION=${NETCDF_VERSION-"3.6.3"}
+export NETCDF_FILE=${NETCDF_FILE-"netcdf-${NETCDF_VERSION}.tar.gz"}
+export NETCDF_COMPATIBILITY_VERSION=${NETCDF_COMPATIBILITY_VERSION-"3.6"}
+export NETCDF_DIR=${NETCDF_DIR-"netcdf-3.6.3"}
 
 export CGNS_FILE=${CGNS_FILE:-"cgnslib_2.4-3.tar.gz"}
 export CGNS_VERSION=${CGNS_VERSION:-"2.4"}
@@ -1179,6 +1183,69 @@ function uncompress_untar
     fi
 }
 
+
+# *************************************************************************** #
+# Function: webget                                                            #
+#                                                                             #
+# Purpose: Downloads a file from the web.                                     #
+#                                                                             #
+# Programmer: Tom Fogal                                                       #
+# Date: Fri Oct  3 10:34:39 MDT 2008                                          #
+#                                                                             #
+# Modifications:                                                              #
+#                                                                             #
+# *************************************************************************** #
+function webget
+{
+    if test "${OPSYS}" = "Darwin" ; then
+        # MaxOS X comes with curl
+        curl -ksfo "$@"
+    else
+        wget ${WGET_OPTS} -o /dev/null "$@"
+        if test $? -ne 0 ; then
+            info "Download of '$@' failed."
+            return 1
+        fi
+    fi
+    return 0
+}
+
+# *************************************************************************** #
+# Function: downloadv                                                         #
+#                                                                             #
+# Purpose: Downloads a file from a list of possible locations.  Stops when    #
+#          a download succeeds.  Each argument should be a mirror of the same #
+#          file.  Dies if the file is unavailable from all locations.         #
+#                                                                             #
+# Programmer: Tom Fogal                                                       #
+# Date: Fri Oct  3 10:30:27 MDT 2008                                          #
+#                                                                             #
+# Modifications:                                                              #
+#                                                                             #
+#   Tom Fogal, Sat May 16 14:40:33 MDT 2009                                   #
+#   Fall back to svn if all else fails.                                       #
+#                                                                             #
+# *************************************************************************** #
+function downloadv
+{
+    for mirror in $@ ; do
+        info "Downloading ${mirror} . . ."
+        webget "${mirror}"
+        if test $? -eq 0 ; then
+            return 0
+        fi
+        info "Download failed.."
+    done
+    # Last chance: try svn.
+    if test "x${DO_SVN}" = "xyes" ; then
+        filename=$(basename "$@[0]")
+        svn cat "${SVN_ROOT_PATH}/trunk/third_party/${filename}" > ${filename}
+        if test $? -eq 0 ; then
+            return 0
+        fi
+    fi
+    error "Could not download any of '$@'."
+}
 
 # *************************************************************************** #
 # Function: download_file                                                     #
