I modified build_visit so that Qt 4.6.1 would compile with gcc 3.2.3 on an x86 platform.  In particular, I added several patches and disabled javascript-jit, script, and scripttools.
git-svn-id: svn+ssh://edison.nersc.gov/project/projectdirs/visit/svn/visit/trunk@10445 18c085ea-50e0-402c-830e-de6fd14e8384

diff --git a/src/svn_bin/build_visit b/src/svn_bin/build_visit
--- a/src/svn_bin/build_visit
+++ b/src/svn_bin/build_visit
@@ -861,6 +861,11 @@
 #     I added several patches for VTK so that VTK would compile under AIX
 #     with cmake 2.8.0.
 #
+#     Eric Brugger, Fri Mar 19 16:04:36 PDT 2010
+#     I added several patches and disabled javascript-jit, script, and
+#     scripttools for Qt 4.6.1 so that it would compile with gcc 3.2.3 on
+#     an x86 platform.
+#
 # *****************************************************************************
 #                                                                             #
 # *************************************************************************** #
@@ -2974,6 +2979,169 @@ fi
 return 0
 }
 
+function apply_qt_461_patch_1
+{
+   patch -p0 <<\EOF
+diff -c a/src/gui/itemviews/qlistview.cpp qt-everywhere-opensource-src-4.6.1/src/gui/itemviews/qlistview.cpp
+*** a/src/gui/itemviews/qlistview.cpp
+--- qt-everywhere-opensource-src-4.6.1/src/gui/itemviews/qlistview.cpp
+***************
+*** 2814,2820 ****
+      if (moved.count() != items.count())
+          moved.resize(items.count());
+  
+!     QRect rect(QPoint(), topLeft);
+      QListViewItem *item = 0;
+      for (int row = info.first; row <= info.last; ++row) {
+          item = &items[row];
+--- 2814,2821 ----
+      if (moved.count() != items.count())
+          moved.resize(items.count());
+  
+!     QPoint zeroPoint;
+!     QRect rect(zeroPoint, topLeft);
+      QListViewItem *item = 0;
+      for (int row = info.first; row <= info.last; ++row) {
+          item = &items[row];
+EOF
+   if [[ $? != 0 ]] ; then
+        warn "Unable to apply patch 1 to Qt 4.6.1"
+        return 1
+   else
+        return 0
+   fi
+}
+
+function apply_qt_461_patch_2
+{
+   patch -p0 <<\EOF
+diff -c a/src/corelib/kernel/qmetaobject.cp qt-everywhere-opensource-src-4.6.1/src/corelib/kernel/qmetaobject.cpp
+*** a/src/corelib/kernel/qmetaobject.cpp
+--- qt-everywhere-opensource-src-4.6.1/src/corelib/kernel/qmetaobject.cpp
+***************
+*** 943,949 ****
+      if (!type || !*type)
+          return result;
+  
+!     QVarLengthArray<char> stackbuf(int(strlen(type)) + 1);
+      qRemoveWhitespace(type, stackbuf.data());
+      int templdepth = 0;
+      qNormalizeType(stackbuf.data(), templdepth, result);
+--- 943,950 ----
+      if (!type || !*type)
+          return result;
+  
+!     int len = int(strlen(type)) + 1;
+!     QVarLengthArray<char> stackbuf(len);
+      qRemoveWhitespace(type, stackbuf.data());
+      int templdepth = 0;
+      qNormalizeType(stackbuf.data(), templdepth, result);
+EOF
+   if [[ $? != 0 ]] ; then
+        warn "Unable to apply patch 2 to Qt 4.6.1"
+        return 1
+   else
+        return 0
+   fi
+}
+
+function apply_qt_461_patch_3
+{
+   patch -p0 <<\EOF
+diff -c a/src/corelib/statemachine/qabstractstate_p.h qt-everywhere-opensource-src-4.6.1/src/corelib/statemachine/qabstractstate_p.h
+*** a/src/corelib/statemachine/qabstractstate_p.h
+--- qt-everywhere-opensource-src-4.6.1/src/corelib/statemachine/qabstractstate_p.h
+***************
+*** 86,92 ****
+      void emitExited();
+  
+      uint stateType:31;
+!     uint isMachine:1;
+      mutable QState *parentState;
+  };
+  
+--- 86,92 ----
+      void emitExited();
+  
+      uint stateType:31;
+!     bool isMachine;
+      mutable QState *parentState;
+  };
+  
+EOF
+   if [[ $? != 0 ]] ; then
+        warn "Unable to apply patch 3 to Qt 4.6.1"
+        return 1
+   else
+        return 0
+   fi
+}
+
+function apply_qt_461_patch_4
+{
+   patch -p0 <<\EOF
+diff -c a/src/plugins/graphicssystems/trace/qgraphicssystem_trace.cpp qt-everywhere-opensource-src-4.6.1/src/plugins/graphicssystems/trace/qgraphicssystem_trace.cpp
+*** a/src/plugins/graphicssystems/trace/qgraphicssystem_trace.cpp
+--- qt-everywhere-opensource-src-4.6.1/src/plugins/graphicssystems/trace/qgraphicssystem_trace.cpp
+***************
+*** 79,85 ****
+  QTraceWindowSurface::~QTraceWindowSurface()
+  {
+      if (buffer) {
+!         QFile outputFile(QString(QLatin1String("qtgraphics-%0.trace")).arg(winId));
+          if (outputFile.open(QIODevice::WriteOnly)) {
+              QDataStream out(&outputFile);
+              out.writeBytes("qttrace", 7);
+--- 79,86 ----
+  QTraceWindowSurface::~QTraceWindowSurface()
+  {
+      if (buffer) {
+!         QString traceFile = QString(QLatin1String("qtgraphics-%0.trace"));
+!         QFile outputFile(traceFile.arg(winId));
+          if (outputFile.open(QIODevice::WriteOnly)) {
+              QDataStream out(&outputFile);
+              out.writeBytes("qttrace", 7);
+EOF
+   if [[ $? != 0 ]] ; then
+        warn "Unable to apply patch 4 to Qt 4.6.1"
+        return 1
+   else
+        return 0
+   fi
+}
+
+function apply_qt_461_patch
+{
+   apply_qt_461_patch_1
+   if [[ $? != 0 ]] ; then
+       return 1
+   fi
+   apply_qt_461_patch_2
+   if [[ $? != 0 ]] ; then
+       return 1
+   fi
+   apply_qt_461_patch_3
+   if [[ $? != 0 ]] ; then
+       return 1
+   fi
+   apply_qt_461_patch_4
+   if [[ $? != 0 ]] ; then
+       return 1
+   fi
+}
+
+function apply_qt_patch
+{
+   if [[ ${QT_VERSION} == 4.6.1 ]] ; then
+       apply_qt_461_patch
+       if [[ $? != 0 ]] ; then
+           return 1
+       fi
+   fi
+
+   return 0
+}
+
 function build_qt
 {
     #
@@ -2981,11 +3149,29 @@ function build_qt
     #
 
     prepare_build_dir $QT_BUILD_DIR $QT_FILE
+    untarred_qt=$?
     # 0, already exists, 1  untarred src, 2 error
 
-    if [[ $? == -1 ]] ; then
+    if [[ untarred_qt == -1 ]] ; then
        warn "Unable to prepare Qt4 build directory. Giving Up!"
        return 1
+    fi
+
+    #
+    # Apply patches
+    #
+    info "Patching qt . . ."
+    apply_qt_patch
+    if [[ $? != 0 ]] ; then
+       if [[ $untarred_qt == 1 ]] ; then
+          warn "Giving up on Qt build because the patch failed."
+          return 1
+       else
+          warn "Patch failed, but continuing.  I believe that this script\n" \
+               "tried to apply a patch to an existing directory which had " \
+               "already been patched ... that is, that the patch is " \
+               "failing harmlessly on a second application."
+       fi
     fi
 
     cd $QT_BUILD_DIR || error "Can't cd to Qt build dir."
@@ -3032,8 +3218,12 @@ function build_qt
     qt_flags="${qt_flags} -no-sql-sqlite2 -no-sql-tds"
     qt_flags="${qt_flags} -no-xmlpatterns"
     qt_flags="${qt_flags} -no-libtiff"
-    #qt_flags="${qt_flags} -no-scripttools" # disable for now -- not in 4.4.3
     qt_flags="${qt_flags} -no-webkit"
+    if [[ ${QT_VERSION} == 4.6.1 ]] ; then
+        qt_flags="${qt_flags} -no-javascript-jit"
+        qt_flags="${qt_flags} -no-script"
+        qt_flags="${qt_flags} -no-scripttools"
+    fi
     info "Configuring Qt4: ./configure --prefix=${VISITDIR}/qt/${QT_VERSION}/${VISITARCH}/" \
          "-platform ${QT_PLATFORM}" \
          "-make libs -make tools -fast -no-separate-debug-info" \
