update to shared build of python
git-svn-id: svn+ssh://edison.nersc.gov/project/projectdirs/visit/svn/visit/trunk@9144 18c085ea-50e0-402c-830e-de6fd14e8384

diff --git a/src/svn_bin/build_visit b/src/svn_bin/build_visit
--- a/src/svn_bin/build_visit
+++ b/src/svn_bin/build_visit
@@ -741,6 +741,11 @@
 #     Quote the PYTHON_EXTRA_LIBS.  Remove CMakeCache.txt file.  Change
 #     the log file to be in the current directory.
 #
+#     Cyrus Harrison, Thu Dec 10 09:13:40 PST 2009
+#     Added rpath linker flags when python is built using gcc.
+#     This is necessary b/c python's build system does not build an exe that
+#     runs without setting LD_LIBRARY_PATH if a non standard prefix is used.
+#
 # *****************************************************************************
 #                                                                             #
 # *************************************************************************** #
@@ -3797,19 +3802,37 @@ function build_python
         cxxFlags=`echo ${CXX_OPT_FLAGS} | sed "s/-qpic/-fPIC/g"`
     fi
     PYTHON_OPT="$cFlags"
+    PYTHON_LDFLAGS=""
+    PYTHON_PREFIX_DIR="$VISITDIR/python/$PYTHON_VERSION/$VISITARCH"
     if [[ "$DO_STATIC_BUILD" == "no" ]]; then
         PYTHON_SHARED="--enable-shared"
+        if [[ "$C_COMPILER" == "gcc" ]]; then
+            #
+            # python's --enable-shared configure flag doesn't link
+            # the exes it builds correclty when installed to a non standard
+            # prefix. To resolve this we need to add a rpath linker flags.
+            #
+            mkdir -p ${PYTHON_PREFIX_DIR}/lib/
+            if [[ $? != 0 ]] ; then
+                 warn "Python configure failed.  Giving up"
+            return 1
+            fi
+
+            PYTHON_LDFLAGS="-Wl,-rpath,${PYTHON_PREFIX_DIR}/lib/"
+        fi
     fi
     if [[ "$OPSYS" == "AIX" ]]; then
         info "Configuring Python (AIX): ./configure OPT=\"$PYTHON_OPT\" CXX=\"$cxxCompiler\" CC=\"$cCompiler\"" \
-             "--prefix=\"$VISITDIR/python/$PYTHON_VERSION/$VISITARCH\" --disable-ipv6"
+             "--prefix=\"$PYTHON_PREFIX_DIR\" --disable-ipv6"
         ./configure OPT="$PYTHON_OPT" CXX="$cxxCompiler" CC="$cCompiler" \
-                --prefix="$VISITDIR/python/$PYTHON_VERSION/$VISITARCH" --disable-ipv6
+                --prefix="$PYTHON_PREFIX_DIR" --disable-ipv6
     else
         info "Configuring Python : ./configure OPT=\"$PYTHON_OPT\" CXX=\"$cxxCompiler\" CC=\"$cCompiler\"" \
-             "${PYTHON_SHARED} --prefix=\"$VISITDIR/python/$PYTHON_VERSION/$VISITARCH\" --disable-ipv6"
-        ./configure OPT="$PYTHON_OPT" CXX="$cxxCompiler" CC="$cCompiler" ${PYTHON_SHARED} \
-                --prefix="$VISITDIR/python/$PYTHON_VERSION/$VISITARCH" --disable-ipv6
+             "LDFLAGS=\"$PYTHON_LDFLAGS\""\
+             "${PYTHON_SHARED} --prefix=\"$PYTHON_PREFIX_DIR\" --disable-ipv6"
+        ./configure OPT="$PYTHON_OPT" CXX="$cxxCompiler" CC="$cCompiler" LDFLAGS="$PYTHON_LDFLAGS" \
+                  ${PYTHON_SHARED} \
+                --prefix="$PYTHON_PREFIX_DIR" --disable-ipv6
     fi
     if [[ $? != 0 ]] ; then
        warn "Python configure failed.  Giving up"
