backporting fixes to ITAPS build logic from trunk for 2.3 release
git-svn-id: svn+ssh://edison.nersc.gov/project/projectdirs/visit/svn/visit/branches/2.3RC@15091 18c085ea-50e0-402c-830e-de6fd14e8384

diff --git a/src/svn_bin/build_visit b/src/svn_bin/build_visit
--- a/src/svn_bin/build_visit
+++ b/src/svn_bin/build_visit
@@ -402,6 +402,9 @@
 #     I changed the script to use mesa 7.8.2 always, since even some linux
 #     platforms had problems building 7.10.2.
 #
+#     Mark C. Miller, Thu Jun 16 22:33:16 PDT 2011
+#     Fixed a number of cases where ITAPS related directory logic was not
+#     including 'itaps/$ITAPS_VERSION' to specify the path.
 # *****************************************************************************
 
 
@@ -1741,19 +1744,25 @@ function check_optional_3rdparty
     fi
     
     if [[ "$DO_ITAPS" == "yes" ]] ; then
-        ensure_built_or_ready "itaps"/$ITAPS_VERSION $ITAPS_MOAB_VERSION $ITAPS_MOAB_BUILD_DIR  $ITAPS_MOAB_FILE $ITAPS_MOAB_URL
+        ensure_built_or_ready "itaps"/$ITAPS_VERSION/MOAB $ITAPS_MOAB_VERSION $ITAPS_MOAB_BUILD_DIR  $ITAPS_MOAB_FILE $ITAPS_MOAB_URL
         if [[ $? != 0 ]] ; then
             ANY_ERRORS="yes"
             DO_ITAPS="no"
             error "Unable to build ITAPS_MOAB.  ${ITAPS_MOAB_FILE} not found."
         fi
-        ensure_built_or_ready "itaps"/$ITAPS_VERSION $ITAPS_FMDB_VERSION $ITAPS_FMDB_BUILD_DIR  $ITAPS_FMDB_FILE $ITAPS_FMDB_URL
+        ensure_built_or_ready "itaps"/$ITAPS_VERSION/FMDB $ITAPS_FMDB_VERSION $ITAPS_FMDB_BUILD_DIR  $ITAPS_FMDB_FILE $ITAPS_FMDB_URL
         if [[ $? != 0 ]] ; then
             ANY_ERRORS="yes"
             DO_ITAPS="no"
             error "Unable to build ITAPS_FMDB.  ${ITAPS_FMDB_FILE} not found."
         fi
-        ensure_built_or_ready "itaps"/$ITAPS_VERSION $ITAPS_GRUMMP_VERSION $ITAPS_GRUMMP_BUILD_DIR  $ITAPS_GRUMMP_FILE $ITAPS_GRUMMP_URL
+        ensure_built_or_ready "itaps"/$ITAPS_VERSION/GRUMMP $ITAPS_GRUMMP_CGM_VERSION $ITAPS_GRUMMP_CGM_BUILD_DIR  $ITAPS_GRUMMP_CGM_FILE $ITAPS_GRUMMP_CGM_URL
+        if [[ $? != 0 ]] ; then
+            ANY_ERRORS="yes"
+            DO_ITAPS="no"
+            error "Unable to build ITAPS_GRUMMP_CGM.  ${ITAPS_GRUMMP_CGM_FILE} not found."
+        fi
+        ensure_built_or_ready "itaps"/$ITAPS_VERSION/GRUMMP $ITAPS_GRUMMP_VERSION $ITAPS_GRUMMP_BUILD_DIR  $ITAPS_GRUMMP_FILE $ITAPS_GRUMMP_URL
         if [[ $? != 0 ]] ; then
             ANY_ERRORS="yes"
             DO_ITAPS="no"
@@ -7580,7 +7589,7 @@ function build_itaps_moab
     fi
     ./configure CXX="$CXX_COMPILER" CC="$C_COMPILER" \
         CFLAGS="$CFLAGS $C_OPT_FLAGS" CXXFLAGS="$CXXFLAGS $CXX_OPT_FLAGS" \
-        --prefix="$VISITDIR/itaps/MOAB/$ITAPS_MOAB_VERSION/$VISITARCH" \
+        --prefix="$VISITDIR/itaps/$ITAPS_VERSION/MOAB/$ITAPS_MOAB_VERSION/$VISITARCH" \
         --with-zlib \
         $WITHHDF5ARG "$WITHSZIPARG" "$WITHNETCDFARG"
     if [[ $? != 0 ]] ; then
@@ -7613,12 +7622,12 @@ function build_itaps_moab
         fi
         # To make it easier to package this build up, ensure we don't wind up
         # liking to shared libraries.
-        find $VISITDIR/itaps/MOAB/$ITAPS_MOAB_VERSION/$VISITARCH -name 'lib*.so*' -exec rm -f {} \;
+        find $VISITDIR/itaps/$ITAPS_VERSION/MOAB/$ITAPS_MOAB_VERSION/$VISITARCH -name 'lib*.so*' -exec rm -f {} \;
     fi
 
     if [[ "$DO_GROUP" == "yes" ]] ; then
-       chmod -R ug+w,a+rX "$VISITDIR/itaps/MOAB"
-       chgrp -R ${GROUP} "$VISITDIR/itaps/MOAB"
+       chmod -R ug+w,a+rX "$VISITDIR/itaps/$ITAPS_VERSION/MOAB"
+       chgrp -R ${GROUP} "$VISITDIR/itaps/$ITAPS_VERSION/MOAB"
     fi
     cd "$START_DIR"
     info "Done with ITAPS_MOAB"
@@ -7673,7 +7682,7 @@ function build_itaps_fmdb
         --with-fmdb=$abs_itaps_fmdb_build_dir \
         --with-scorecutil=$abs_itaps_fmdb_build_dir/SCUtil/SCORECUtil-0.1 \
         --with-iterators=$abs_itaps_fmdb_build_dir/SCUtil/siter \
-        --prefix="$VISITDIR/itaps/FMDB/$ITAPS_FMDB_VERSION/$VISITARCH"
+        --prefix="$VISITDIR/itaps/$ITAPS_VERSION/FMDB/$ITAPS_FMDB_VERSION/$VISITARCH"
     if [[ $? != 0 ]] ; then
        warn "ITAPS_FMBD configure failed.  Giving up"
        return 1
@@ -7702,10 +7711,10 @@ function build_itaps_fmdb
     pushd SCUtil/SCORECUtil-0.1 >/dev/null 2>&1
     ./configure CXX="$CXX_COMPILER" CC="$C_COMPILER" \
         CFLAGS="$CFLAGS $C_OPT_FLAGS" CXXFLAGS="$CXXFLAGS $CXX_OPT_FLAGS" \
-        --with-gmi=$VISITDIR/itaps/FMDB/$ITAPS_FMDB_VERSION/$VISITARCH \
+        --with-gmi=$VISITDIR/itaps/$ITAPS_VERSION/FMDB/$ITAPS_FMDB_VERSION/$VISITARCH \
         --with-fmdb=$abs_itaps_fmdb_build_dir \
         --with-iterators=$abs_itaps_fmdb_build_dir/SCUtil/siter \
-        --prefix="$VISITDIR/itaps/FMDB/$ITAPS_FMDB_VERSION/$VISITARCH"
+        --prefix="$VISITDIR/itaps/$ITAPS_VERSION/FMDB/$ITAPS_FMDB_VERSION/$VISITARCH"
     if [[ $? != 0 ]] ; then
        warn "ITAPS_FMBD configure failed.  Giving up"
        return 1
@@ -7733,10 +7742,10 @@ function build_itaps_fmdb
     info "Invoking command to configure ITAPS_FMDB"
     ./configure CXX="$CXX_COMPILER" CC="$C_COMPILER" \
         CFLAGS="$CFLAGS $C_OPT_FLAGS" CXXFLAGS="$CXXFLAGS $CXX_OPT_FLAGS" \
-        --with-scorecutil=$VISITDIR/itaps/FMDB/$ITAPS_FMDB_VERSION/$VISITARCH \
-        --with-gmi=$VISITDIR/itaps/FMDB/$ITAPS_FMDB_VERSION/$VISITARCH \
+        --with-scorecutil=$VISITDIR/itaps/$ITAPS_VERSION/FMDB/$ITAPS_FMDB_VERSION/$VISITARCH \
+        --with-gmi=$VISITDIR/itaps/$ITAPS_VERSION/FMDB/$ITAPS_FMDB_VERSION/$VISITARCH \
         --with-iterators=$abs_itaps_fmdb_build_dir/SCUtil/siter \
-        --prefix="$VISITDIR/itaps/FMDB/$ITAPS_FMDB_VERSION/$VISITARCH" \
+        --prefix="$VISITDIR/itaps/$ITAPS_VERSION/FMDB/$ITAPS_FMDB_VERSION/$VISITARCH" \
         --enable-imesh
     if [[ $? != 0 ]] ; then
        warn "ITAPS_FMBD configure failed.  Giving up"
@@ -7768,12 +7777,12 @@ function build_itaps_fmdb
         fi
         # To make it easier to package this build up, ensure we don't wind up
         # liking to shared libraries.
-        find $VISITDIR/itaps/FMDB/$ITAPS_FMDB_VERSION/$VISITARCH -name 'lib*.so*' -exec rm -f {} \;
+        find $VISITDIR/itaps/$ITAPS_VERSION/FMDB/$ITAPS_FMDB_VERSION/$VISITARCH -name 'lib*.so*' -exec rm -f {} \;
     fi
 
     if [[ "$DO_GROUP" == "yes" ]] ; then
-       chmod -R ug+w,a+rX "$VISITDIR/itaps/FMDB"
-       chgrp -R ${GROUP} "$VISITDIR/itaps/FMDB"
+       chmod -R ug+w,a+rX "$VISITDIR/itaps/$ITAPS_VERSION/FMDB"
+       chgrp -R ${GROUP} "$VISITDIR/itaps/$ITAPS_VERSION/FMDB"
     fi
     cd "$START_DIR"
     info "Done with ITAPS_FMDB"
@@ -7804,7 +7813,7 @@ function build_itaps_grummp
     info "Invoking command to configure ITAPS_GRUMMP_CGM"
     ./configure CXX="$CXX_COMPILER" CC="$C_COMPILER" \
         CFLAGS="$CFLAGS $C_OPT_FLAGS" CXXFLAGS="$CXXFLAGS $CXX_OPT_FLAGS" \
-        --prefix="$VISITDIR/itaps/GRUMMP/$ITAPS_GRUMMP_VERSION/$VISITARCH"
+        --prefix="$VISITDIR/itaps/$ITAPS_VERSION/GRUMMP/$ITAPS_GRUMMP_VERSION/$VISITARCH"
     if [[ $? != 0 ]] ; then
        warn "ITAPS_GRUMMP_CGM configure failed.  Giving up"
        return 1
@@ -7835,13 +7844,14 @@ function build_itaps_grummp
         fi
         # To make it easier to package this build up, ensure we don't wind up
         # liking to shared libraries.
-        find $VISITDIR/itaps/GRUMMP/$ITAPS_GRUMMP_VERSION/$VISITARCH -name 'lib*.so*' -exec rm -f {} \;
+        find $VISITDIR/itaps/$ITAPS_VERSION/GRUMMP/$ITAPS_GRUMMP_VERSION/$VISITARCH -name 'lib*.so*' -exec rm -f {} \;
     fi
 
     if [[ "$DO_GROUP" == "yes" ]] ; then
-       chmod -R ug+w,a+rX "$VISITDIR/itaps/GRUMMP"
-       chgrp -R ${GROUP} "$VISITDIR/itaps/GRUMMP"
+       chmod -R ug+w,a+rX "$VISITDIR/itaps/$ITAPS_VERSION/GRUMMP"
+       chgrp -R ${GROUP} "$VISITDIR/itaps/$ITAPS_VERSION/GRUMMP"
     fi
+    cd "$START_DIR"
     info "Done with ITAPS_GRUMMP_CGM"
 
     #
@@ -7862,8 +7872,8 @@ function build_itaps_grummp
     info "Invoking command to configure ITAPS_GRUMMP"
     ./configure CXX="$CXX_COMPILER" CC="$C_COMPILER" \
         CFLAGS="$CFLAGS $C_OPT_FLAGS" CXXFLAGS="$CXXFLAGS $CXX_OPT_FLAGS" \
-        --prefix="$VISITDIR/itaps/GRUMMP/$ITAPS_GRUMMP_VERSION/$VISITARCH" \
-        --with-CGM-path="$VISITDIR/itaps/GRUMMP/$ITAPS_GRUMMP_VERSION/$VISITARCH" \
+        --prefix="$VISITDIR/itaps/$ITAPS_VERSION/GRUMMP/$ITAPS_GRUMMP_VERSION/$VISITARCH" \
+        --with-CGM-path="$VISITDIR/itaps/$ITAPS_VERSION/GRUMMP/$ITAPS_GRUMMP_VERSION/$VISITARCH" \
         --enable-imesh
     if [[ $? != 0 ]] ; then
        warn "ITAPS_GRUMMP configure failed.  Giving up"
@@ -7895,12 +7905,12 @@ function build_itaps_grummp
         fi
         # To make it easier to package this build up, ensure we don't wind up
         # liking to shared libraries.
-        find $VISITDIR/itaps/GRUMMP/$ITAPS_GRUMMP_VERSION/$VISITARCH -name 'lib*.so*' -exec rm -f {} \;
+        find $VISITDIR/itaps/$ITAPS_VERSION/GRUMMP/$ITAPS_GRUMMP_VERSION/$VISITARCH -name 'lib*.so*' -exec rm -f {} \;
     fi
 
     if [[ "$DO_GROUP" == "yes" ]] ; then
-       chmod -R ug+w,a+rX "$VISITDIR/itaps/GRUMMP"
-       chgrp -R ${GROUP} "$VISITDIR/itaps/GRUMMP"
+       chmod -R ug+w,a+rX "$VISITDIR/itaps/$ITAPS_VERSION/GRUMMP"
+       chgrp -R ${GROUP} "$VISITDIR/itaps/$ITAPS_VERSION/GRUMMP"
     fi
     cd "$START_DIR"
     info "Done with ITAPS_GRUMMP"
@@ -8671,29 +8681,29 @@ function build_hostconf
         echo "## ITAPS" >> $HOSTCONF
         echo "##" >> $HOSTCONF
         echo "## MOAB implementation" >> $HOSTCONF
-        echo "ITAPS_INCLUDE_DIRECTORIES(MOAB \${VISITHOME}/itaps/MOAB/$ITAPS_MOAB_VERSION/\${VISITARCH}/include)" \
+        echo "ITAPS_INCLUDE_DIRECTORIES(MOAB \${VISITHOME}/itaps/$ITAPS_VERSION/MOAB/$ITAPS_MOAB_VERSION/\${VISITARCH}/include)" \
         >> $HOSTCONF
         echo "ITAPS_FILE_PATTERNS(MOAB *.cub)" >> $HOSTCONF
         echo "ITAPS_LINK_LIBRARIES(MOAB iMesh MOAB hdf5 sz z netcdf_c++ netcdf vtkGraphics)" \
         >> $HOSTCONF
         echo "ITAPS_LINK_DIRECTORIES(MOAB " \
-             "\${VISITHOME}/itaps/MOAB/$ITAPS_MOAB_VERSION/\${VISITARCH}/lib " \
+             "\${VISITHOME}/itaps/$ITAPS_VERSION/MOAB/$ITAPS_MOAB_VERSION/\${VISITARCH}/lib " \
              "\${VISITHOME}/hdf5/${HDF5_VERSION}/\${VISITARCH}/lib " \
              "\${VISITHOME}/szip/${SZIP_VERSION}/\${VISITARCH}/lib " \
              "\${VISITHOME}/netcdf/${NETCDF_VERSION}/\${VISITARCH}/lib)" >> $HOSTCONF
         echo "## FMDB implementation" >> $HOSTCONF
-        echo "ITAPS_INCLUDE_DIRECTORIES(FMDB \${VISITHOME}/itaps/FMDB/$ITAPS_FMDB_VERSION/\${VISITARCH}/include)" \
+        echo "ITAPS_INCLUDE_DIRECTORIES(FMDB \${VISITHOME}/itaps/$ITAPS_VERSION/FMDB/$ITAPS_FMDB_VERSION/\${VISITARCH}/include)" \
         >> $HOSTCONF
         echo "ITAPS_FILE_PATTERNS(FMDB *.sms)" >> $HOSTCONF
         echo "ITAPS_LINK_LIBRARIES(FMDB FMDB SCORECModel SCORECUtil vtkGraphics)" >> $HOSTCONF
-        echo "ITAPS_LINK_DIRECTORIES(FMDB \${VISITHOME}/itaps/FMDB/$ITAPS_FMDB_VERSION/\${VISITARCH}/lib)" >> $HOSTCONF
+        echo "ITAPS_LINK_DIRECTORIES(FMDB \${VISITHOME}/itaps/$ITAPS_VERSION/FMDB/$ITAPS_FMDB_VERSION/\${VISITARCH}/lib)" >> $HOSTCONF
         echo "## GRUMMP implementation" >> $HOSTCONF
-        echo "ITAPS_INCLUDE_DIRECTORIES(GRUMMP \${VISITHOME}/itaps/GRUMMP/$ITAPS_GRUMMP_VERSION/\${VISITARCH}/include)" \
+        echo "ITAPS_INCLUDE_DIRECTORIES(GRUMMP \${VISITHOME}/itaps/$ITAPS_VERSION/GRUMMP/$ITAPS_GRUMMP_VERSION/\${VISITARCH}/include)" \
         >> $HOSTCONF
         echo "ITAPS_FILE_PATTERNS(GRUMMP *.bdry *.smesh *.vmesh)" >> $HOSTCONF
         echo "ITAPS_LINK_LIBRARIES(GRUMMP iMesh_GRUMMP GR_3D GR_surf GR_2D GR_geom GR_base SUMAAlog_lite OptMS vtkGraphics cgm dl)" \
         >> $HOSTCONF
-        echo "ITAPS_LINK_DIRECTORIES(GRUMMP \${VISITHOME}/itaps/GRUMMP/$ITAPS_GRUMMP_VERSION/\${VISITARCH}/lib)" \
+        echo "ITAPS_LINK_DIRECTORIES(GRUMMP \${VISITHOME}/itaps/$ITAPS_VERSION/GRUMMP/$ITAPS_GRUMMP_VERSION/\${VISITARCH}/lib)" \
         >> $HOSTCONF
     fi
 
@@ -10283,7 +10293,7 @@ cd "$START_DIR"
 if [[ "$DO_ITAPS" == "yes" ]] ; then
 
     # handle MOAB implementation of ITAPS
-    check_if_installed "itaps/MOAB" $ITAPS_MOAB_VERSION
+    check_if_installed "itaps/$ITAPS_VERSION/MOAB" $ITAPS_MOAB_VERSION
     if [[ $? == 0 ]] ; then
         info "Skipping ITAPS_MOAB build.  ITAPS_MOAB is already installed."
     else
@@ -10296,7 +10306,7 @@ if [[ "$DO_ITAPS" == "yes" ]] ; then
     fi
 
     # handle FMDB implementation of ITAPS
-    check_if_installed "itaps/FMDB" $ITAPS_FMDB_VERSION
+    check_if_installed "itaps/$ITAPS_VERSION/FMDB" $ITAPS_FMDB_VERSION
     if [[ $? == 0 ]] ; then
         info "Skipping ITAPS_FMDB build.  ITAPS_FMDB is already installed."
     else
@@ -10309,7 +10319,7 @@ if [[ "$DO_ITAPS" == "yes" ]] ; then
     fi
 
     # handle GRUMMP implementation ot ITAPS
-    check_if_installed "itaps/GRUMMP" $ITAPS_GRUMMP_VERSION
+    check_if_installed "itaps/$ITAPS_VERSION/GRUMMP" $ITAPS_GRUMMP_VERSION
     if [[ $? == 0 ]] ; then
         info "Skipping ITAPS_GRUMMP build.  ITAPS_GRUMMP is already installed."
     else
