initial pyside support
git-svn-id: svn+ssh://edison.nersc.gov/project/projectdirs/visit/svn/visit/trunk@16362 18c085ea-50e0-402c-830e-de6fd14e8384

diff --git a/src/svn_bin/build_visit b/src/svn_bin/build_visit
--- a/src/svn_bin/build_visit
+++ b/src/svn_bin/build_visit
@@ -40,7 +40,7 @@
 #       current directory.  If it does not locate these libraries, it will
 #       try to download them.
 #       You must have:
-#          Qt       qt-everywhere-opensource-src-4.6.1.tar.gz
+#          Qt       qt-everywhere-opensource-src-4.7.4.tar.gz
 #          Mesa     MesaLib-7.10.2.tar.gz
 #          Python   Python-2.6.4tgz
 #          VTK      vtk-5.8.0.tar.gz
@@ -82,6 +82,7 @@
 #     Function 2.2, check_variables:edit variable build information
 #     Function 3, build_mesa:       build mangled Mesa
 #     Function 4, build_qt:         build Qt
+#     Function 4.2, build_pyside    build pyside python/qt support
 #     Function 5, build_cmake:      build CMake (like configure, for VTK)
 #     Function 6, build_vtk:        build VTK
 #     Function 7, build_python:     build Python
@@ -475,6 +476,9 @@
 #     Cyrus Harrison, Thu Sep 15 16:47:18 PDT 2011
 #     Disable fortran support if a fortran compiler was not specified or found.
 #
+#     Cyrus Harrison, Wed Sep 28 11:13:52 PDT 2011
+#     Updated to Qt 4.7.4 & added PySide support.
+#
 # *****************************************************************************
 
 
@@ -691,6 +695,8 @@ export DO_MESA="no"
 export ON_MESA="off"
 export DO_QT="no"
 export ON_QT="off"
+export DO_PYSIDE="no"
+export ON_PYSIDE="off"
 export DO_CMAKE="no"
 export ON_CMAKE="off"
 export DO_VTK="no"
@@ -877,10 +883,13 @@ export PIL_BUILD_DIR=${PIL_BUILD_DIR:-"Imaging-1.1.6"}
 export PYPARSING_FILE=${PYPARSING_FILE:-"pyparsing-1.5.2.tar.gz"}
 export PYPARSING_BUILD_DIR=${PYPARSING_BUILD_DIR:-"pyparsing-1.5.2"}
 
-export QT_FILE=${QT_FILE:-"qt-everywhere-opensource-src-4.6.1.tar.gz"}
-export QT_VERSION=${QT_VERSION:-"4.6.1"}
-
+export QT_FILE=${QT_FILE:-"qt-everywhere-opensource-src-4.7.4.tar.gz"}
+export QT_VERSION=${QT_VERSION:-"4.7.4"}
 export QT_BUILD_DIR=${QT_BUILD_DIR:-"${QT_FILE%.tar*}"}
+
+export PYSIDE_FILE=${PYSIDE_FILE:-"pyside-combined-1.0.7.tar.gz"}
+export PYSIDE_VERSION=${PYSIDE_VERSION:-"1.0.7"}
+export PYSIDE_BUILD_DIR=${PYSIDE_BUILD_DIR:-"${PYSIDE_FILE%.tar*}"}
 
 export SZIP_FILE=${SZIP_FILE:-"szip-2.1.tar.gz"}
 export SZIP_VERSION=${SZIP_VERSION:-"2.1"}
@@ -1739,6 +1748,9 @@ function check_visit_source_code
 #    Added pass of BOXLIB_VERSION to ensure_built_or_ready, now that boxlib
 #    has a version number.
 #
+#    Cyrus Harrison, Wed Sep 28 11:13:52 PDT 2011
+#    Added PySide Support.
+#
 # *************************************************************************** #
 
 function check_optional_3rdparty
@@ -1984,6 +1996,15 @@ function check_optional_3rdparty
             ANY_ERRORS="yes"
             DO_ICET="no"
             error "Unable to build Ice-T.  ${ICET_FILE} not found."
+        fi
+    fi
+    
+    if [[ "$DO_PYSIDE" = "yes" ]] ; then
+        ensure_built_or_ready "pyside"     $PYSIDE_VERSION    $PYSIDE_BUILD_DIR    $PYSIDE_FILE
+        if [[ $? != 0 ]] ; then
+            ANY_ERRORS="yes"
+            DO_PYSIDE="no"
+            error "Unable to build PySide.  ${PYSIDE_FILE} not found."
         fi
     fi
 }
@@ -3421,20 +3442,13 @@ function build_qt
     qt_flags="${qt_flags} -no-sql-db2 -no-sql-ibase -no-sql-mysql -no-sql-oci"
     qt_flags="${qt_flags} -no-sql-odbc -no-sql-psql -no-sql-sqlite"
     qt_flags="${qt_flags} -no-sql-sqlite2 -no-sql-tds"
-    qt_flags="${qt_flags} -no-xmlpatterns"
     qt_flags="${qt_flags} -no-libtiff"
     qt_flags="${qt_flags} -no-libjpeg"
-    qt_flags="${qt_flags} -no-webkit"
     qt_flags="${qt_flags} -nomake docs" 
     qt_flags="${qt_flags} -nomake examples" 
     qt_flags="${qt_flags} -nomake demos" 
     qt_flags="${qt_flags} -opensource" 
     qt_flags="${qt_flags} -confirm-license"
-    if [[ ${QT_VERSION} == 4.6.1 ]] ; then
-        qt_flags="${qt_flags} -no-javascript-jit"
-        qt_flags="${qt_flags} -no-script"
-        qt_flags="${qt_flags} -no-scripttools"
-    fi
     info "Configuring Qt4: ./configure --prefix=${VISITDIR}/qt/${QT_VERSION}/${VISITARCH}/" \
          "-platform ${QT_PLATFORM}" \
          "-make libs -make tools -fast -no-separate-debug-info" \
@@ -3528,6 +3542,122 @@ function build_qt
 
     cd "$START_DIR"
     info "Done with Qt4"
+
+    return 0
+}
+
+# *************************************************************************** #
+#                          Function 4.2, build_pyside                          #
+# *************************************************************************** #
+
+function build_pyside_component
+{
+    CMAKE_BIN="$VISITDIR/cmake/${CMAKE_VERSION}/$VISITARCH/bin/cmake"
+    VISIT_PYSIDE_DIR=${VISITDIR}/pyside/${PYSIDE_VERSION}/${VISITARCH}/
+    QTDIR=${VISITDIR}/qt/${QT_VERSION}/${VISITARCH}/
+    QTLIBDIR=${QTDIR}/lib/
+    
+    export PATH=${QTBINDIR}:$PATH
+    export PATH=$VISIT_PYSIDE_DIR/bin:$VISIT_PYTHON_DIR/bin:$PATH
+    export PYTHONPATH=$VISIT_PYSIDE_DIR/lib/python${PYTHON_COMPATIBILITY_VERSION}/site-packages:$PYTHONPATH
+    export PKG_CONFIG_PATH=$VISIT_PYSIDE_DIR/lib/pkgconfig:$PKG_CONFIG_PATH
+
+    
+    QMAKEEXE=${QTDIR}/bin/qmake
+    QMAKEINCDIR=${QTDIR}/include
+    CMAKE_PROG=${VISITDIR}/cmake/${CMAKE_VERSION}/$VISITARCH/bin/cmake
+    PYTHON_DIR=${VISITDIR}/python/${PYTHON_VERSION}/$VISITARCH/
+
+    PYTHON_BINARY=${PYTHON_DIR}/bin/python
+    PYTHON_LIBRARY_DIR=${PYTHON_DIR}/lib
+    PYTHON_INCLUDE_DIR=${PYTHON_DIR}/include/python${PYTHON_COMPATIBILITY_VERSION}
+    PYTHON_LIBRARY=${PYTHON_DIR}/lib/libpython${PYTHON_COMPATIBILITY_VERSION}.${SO_EXT}
+    PYTHON_LIBS=${PYTHON_DIR}/lib/
+
+    cd $1
+    info "Configuring pyside/$1 . . ."
+    $CMAKE_BIN . \
+        -DCMAKE_INSTALL_PREFIX:FILEPATH=$VISIT_PYSIDE_DIR \
+        -DCMAKE_SKIP_BUILD_RPATH:BOOL=FALSE\
+        -DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=FALSE\
+        -DCMAKE_INSTALL_RPATH:FILEPATH=$VISIT_PYSIDE_DIR/lib \
+        -DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=TRUE\
+        -DCMAKE_INSTALL_NAME_DIR:FILEPATH=$VISIT_PYSIDE_DIR/lib \
+        -DCMAKE_BUILD_TYPE:STRING=Release \
+        -DALTERNATIVE_QT_INCLUDE_DIR:FILEPATH=$QMAKEINCDIR \
+        -DQT_QMAKE_EXECUTABLE:FILEPATH=$QMAKEEXE \
+        -DENABLE_ICECC:BOOL=0 \
+        -DShiboken_DIR:FILEPATH=$VISIT_PYSIDE_DIR/lib/\
+        -DPYTHON_EXECUTABLE:FILEPATH=$PYTHON_BINARY\
+        -DPYTHON_INCLUDE_PATH:FILEPATH=$PYTHON_INCLUDE_DIR\
+        -DPYTHON_LIBRARY:FILEPATH=$PYTHON_LIBRARY\
+        -DDISABLE_DOCSTRINGS:BOOL=True
+    
+    if [[ $? != 0 ]] ; then
+       warn "Cannot configure pyside/$1, giving up."
+       return 1
+    fi
+
+    info "Building pyside/$1 . . ."
+    $MAKE $MAKE_OPT_FLAGS
+    if [[ $? != 0 ]] ; then
+       warn "Cannot build pyside/$1, giving up."
+       return 1
+    fi
+
+    info "Installing pyside/$1 . . ."
+    $MAKE install
+    info "Successfully built pyside/$1"
+    cd ../
+}
+
+function build_pyside
+{
+    ##
+    ## Prepare the build dir using src file.
+    ##
+
+    prepare_build_dir $PYSIDE_BUILD_DIR $PYSIDE_FILE
+    untarred_pyside=$?
+    ## 0, already exists, 1  untarred src, 2 error
+
+    if [[ untarred_pyside == -1 ]] ; then
+       warn "Unable to prepare PySide build directory. Giving Up!"
+       return 1
+    fi
+    
+    cd $PYSIDE_BUILD_DIR || error "Can't cd to PySide build dir."
+
+    
+    build_pyside_component apiextractor-0.10.7
+    if [[ $? != 0 ]] ; then
+       return 1
+    fi
+
+    build_pyside_component generatorrunner-0.6.13		
+    if [[ $? != 0 ]] ; then
+       return 1
+    fi
+    
+    build_pyside_component shiboken-1.0.7
+    if [[ $? != 0 ]] ; then
+       return 1
+    fi
+    
+    build_pyside_component pyside-qt4.7+1.0.7
+    if [[ $? != 0 ]] ; then
+       return 1
+    fi
+
+    if [[ "$DO_GROUP" == "yes" ]] ; then
+       chmod -R ug+w,a+rX "$VISITDIR/pyside"
+       chgrp -R ${GROUP} "$VISITDIR/pyside"
+    fi
+
+    cd "$START_DIR"
+    info "Linking PySide to Python Installation"
+    ln -s $VISIT_PYSIDE_DIR/lib/python${PYTHON_COMPATIBILITY_VERSION}/site-packages/PySide $PYTHON_DIR/lib/python${PYTHON_COMPATIBILITY_VERSION}/site-packages/PySide
+    info "Done with PySide"
 
     return 0
 }
@@ -8490,8 +8620,7 @@ function build_hostconf
     echo "VISIT_OPTION_DEFAULT(VISIT_QT_BIN \${VISITHOME}/qt/$QT_VERSION/\${VISITARCH}/bin)" >> $HOSTCONF
     echo >> $HOSTCONF
     echo "##" >> $HOSTCONF
-    echo \
-"## Specify the location of the python." >> $HOSTCONF
+    echo "## Specify the location of the python." >> $HOSTCONF
     echo "##" >> $HOSTCONF
     if [[ "$VISIT_PYTHON_DIR" != "" ]]; then
         echo "VISIT_OPTION_DEFAULT(VISIT_PYTHON_DIR $VISIT_PYTHON_DIR)" >> $HOSTCONF
@@ -8499,6 +8628,13 @@ function build_hostconf
         echo "VISIT_OPTION_DEFAULT(VISIT_PYTHON_DIR \${VISITHOME}/python/$PYTHON_VERSION/\${VISITARCH})" >> $HOSTCONF
     fi
     echo >> $HOSTCONF
+    if [[ "$DO_PYSIDE" == "yes" ]] ; then
+        echo "##" >> $HOSTCONF
+        echo "## Specify the PySide dir. " >> $HOSTCONF
+        echo "##" >> $HOSTCONF
+        echo "VISIT_OPTION_DEFAULT(VISIT_PYSIDE_DIR \${VISITHOME}/pyside/$PYSIDE_VERSION/\${VISITARCH}/)" >> $HOSTCONF
+        echo >> $HOSTCONF
+    fi
     echo "##" >> $HOSTCONF
     echo "## Compiler flags." >> $HOSTCONF
     echo "##" >> $HOSTCONF
@@ -9108,6 +9244,11 @@ printvariables () {
   printf "%s%s\n" "QT_PLATFORM=" "${QT_PLATFORM}"
   printf "%s%s\n" "QT_BUILD_DIR=" "${QT_BUILD_DIR}"
 
+  printf "%s%s\n" "PYSIDE_FILE=" "${PYSIDE_FILE}"
+  printf "%s%s\n" "PYSIDE_VERSION=" "${PYSIDE_VERSION}"
+  printf "%s%s\n" "PYSIDE_PLATFORM=" "${PYSIDE_PLATFORM}"
+  printf "%s%s\n" "PYSIDE_BUILD_DIR=" "${PYSIDE_BUILD_DIR}"
+
   printf "%s%s\n" "TCMALLOC_FILE=" "${TCMALLOC_FILE}"
   printf "%s%s\n" "TCMALLOC_VERSION=" "${TCMALLOC_VERSION}"
   printf "%s%s\n" "TCMALLOC_COMPATIBILITY_VERSION=" "${TCMALLOC_COMPATIBILITY_VERSION}"
@@ -9515,6 +9656,7 @@ for arg in "${arguments[@]}" ; do
         --python) DO_PYTHON="yes"; ON_PYTHON="on";;
         --python-module) DO_MODULE="yes"; ON_MODULE="on";;
         --qt) DO_QT="yes"; ON_QT="on";;
+        --pyside) DO_PYSIDE="yes"; ON_PYSIDE="on";;
         --relative) ABS_PATH="no"; ON_ABS_PATH="off";;
         --silo) DO_SILO="yes"; ON_SILO="on";;
         --szip) DO_SZIP="yes"; ON_SZIP="on";;
@@ -10208,6 +10350,25 @@ if [[ "$DO_QT" == "yes" ]] ; then
       info "Done building Qt4"
    fi
 fi
+
+#
+# Build PySide
+#
+cd "$START_DIR"
+if [[ "$DO_PYSIDE" == "yes" ]] ; then
+        check_if_installed "pyside" $PYSIDE_VERSION
+    if [[ $? == 0 ]] ; then
+        info "Skipping PySide build.  PySide is already installed."
+   else
+      info "Building PySide (~10 minutes)"
+      build_pyside
+      if [[ $? != 0 ]] ; then
+         error "Unable to build or install PySide.  Bailing out."
+      fi
+      info "Done building PySide"
+   fi
+fi
+
 
 cd "$START_DIR"
 if [[ "$DO_SZIP" == "yes" ]] ; then
