Merge RC trunk into trunk
git-svn-id: svn+ssh://edison.nersc.gov/project/projectdirs/visit/svn/visit/trunk@1334 18c085ea-50e0-402c-830e-de6fd14e8384

diff --git a/src/svn_bin/merge_rcbranch_to_rctrunk b/src/svn_bin/merge_rcbranch_to_rctrunk
--- a/src/svn_bin/merge_rcbranch_to_rctrunk
+++ b/src/svn_bin/merge_rcbranch_to_rctrunk
@@ -1,17 +1,14 @@
 #!/bin/ksh
 #
-#  Script: merge_branch_to_trunk
+#  Script: merge_rcbranch_to_rctrunk
 # 
 #  Purpose: 
-#      Merges a branch into the trunk
+#      Merges a RC branch into the RC trunk
 #
 #  Programmer: Hank Childs
-#  Creation:   May 15, 2007
+#  Creation:   June 23, 2007
 #
 #  Modifications:
-#
-#    Hank Childs, Sat Jun 23 16:47:06 PDT 2007
-#    Disallow merging from an RC branch to the trunk.
 #
 # *****************************************************************************
 
@@ -39,7 +36,8 @@ elif [[ ! -f .rootpath ]] ; then
    echo ""
    issueHelp="yes"
 else
-   TRUNKNAME=$(cat .branchname)
+   T2=$(cat .branchname) 
+   TRUNKNAME=${T2#*RC_}  # strip off 1.6.1RC_trunk to make trunk
    if [[ "$TRUNKNAME" != "trunk" ]] ; then
       echo "You must be in the trunk when you run this script"
       echo ""
@@ -89,9 +87,9 @@ if [[ "$issueHelp" == "yes" ]] ; then
    echo ""
    echo "Usage:   ${0##*/} <branch>"
    echo ""
-   echo "Example: ${0##*/} my_dev_work"
-   echo "\tshould be run at the top level of your checked out trunk.  It will "
-   echo "\tmerge the work from my_dev_work into the trunk."
+   echo "Example: ${0##*/} my_rc_dev_work"
+   echo "\tshould be run at the top level of your checked out RC trunk.  It will "
+   echo "\tmerge the work from my_rc_dev_work into the RC trunk."
    echo ""
    
    exit 1
@@ -107,24 +105,19 @@ mkdir tmp_forRev$$
 cd tmp_forRev$$
 svn co ${VISIT_SVN_BRANCHES}/${SVN_NERSC_NAME}/${BRANCHNAME}/svninfo
 cd svninfo
-REV=$(cat Rev_toTrunk)
-isRC="no"
-if [[ -f Rev_toRCTrunk ]] ; then
-   isRC="yes"
+if [[ ! -f Rev_toRCTrunk ]] ; then
+   REV="not_found"
+else
+   REV=$(cat Rev_toRCTrunk)
 fi
 cd ../..
-if [[ "$isRC" == "yes" ]] ; then
-   echo ""
-   echo "I believe the branch you are trying to merge from is an RC branch."
-   echo ""
-   echo "RC branches must be merged onto the RC trunk."
-   echo "The RC trunk can then be merged to using merge_rctrunk_to_trunk."
-   echo ""
-   echo "Aborting!"
-   echo ""
-   rm -Rf tmp_forRev$$
-   exit 1
+if [[ "$REV" == "not_found" ]] ; then
+   echo "Could not locate file Rev_toRCTrunk."
+   echo "I do not believe this is an RC branch."
+   echo "Aborting"
+   exit 1 
 fi
+
 echo ""
 echo "The revision of the last merge was $REV"
 echo ""
@@ -142,7 +135,7 @@ done
 NEW_REV=$(get_latest_rev)
 
 cd tmp_forRev$$/svninfo
-echo "$NEW_REV" > Rev_toTrunk
+echo "$NEW_REV" > Rev_toRCTrunk
 echo ""
 echo "Updating branch $BRANCHNAME to contain a record of this merge"
 echo ""
@@ -158,7 +151,7 @@ echo "merge took place and future merges into the trunk will not attempt to merg
 echo "these revisions again.  If you want to back out this merge, you will need "
 echo "invoke the following command to update our bookkeeping: "
 echo ""
-echo "  set_branch_to_trunk_revision $BRANCHNAME $REV"
+echo "  set_branch_to_trunk_revision $BRANCHNAME $REV RC"
 echo ""
 
 return 0
