updating to capture stdout/stderr from make into different files; added warning switches
git-svn-id: svn+ssh://edison.nersc.gov/project/projectdirs/visit/svn/visit/trunk@23729 18c085ea-50e0-402c-830e-de6fd14e8384

diff --git a/src/svn_bin/regressiontest_edge b/src/svn_bin/regressiontest_edge
--- a/src/svn_bin/regressiontest_edge
+++ b/src/svn_bin/regressiontest_edge
@@ -242,7 +242,11 @@ fi
     -DCMAKE_C_FLAGS_DEBUG:STRING="-Wall -pedantic -Wextra -Wno-long-long -Wno-unused-parameter" \
     . >> ../buildlog 2>&1
 rm -rf ../make.out ../make.err
-make -j 12 1>../make.out 2>../make.err
+make -k -j 12 1>../make.out 2>../make.err
+if test $? -ne 0; then
+    echo "Source build FAILED at: \`date\`" | mail -s "Source build FAILED" $userEmail
+    exit 1
+fi
 if test "$debug" = "true" ; then
     echo "Source build completed at: \`date\`" | mail -s "Source build completed" $userEmail
 fi
