updating regression scripts to do make-clean/distclean BEFORE doing svn update; restricting emails from LLNL testing to LLNL developers
git-svn-id: svn+ssh://edison.nersc.gov/project/projectdirs/visit/svn/visit/trunk@8035 18c085ea-50e0-402c-830e-de6fd14e8384

diff --git a/src/svn_bin/regressiontest_davinci b/src/svn_bin/regressiontest_davinci
--- a/src/svn_bin/regressiontest_davinci
+++ b/src/svn_bin/regressiontest_davinci
@@ -129,6 +129,12 @@
 #
 #    Mark C. Miller, Thu Jul 30 08:23:14 PDT 2009
 #    Made it count fact that script was changed as +1 in numChangedFiles.
+#
+#    Mark C. Miller, Mon Aug  3 12:51:27 PDT 2009
+#    Changed order of operations so that make clean and make distclean
+#    occur BEFORE svn update. That way, any dirs that might have been created
+#    during a previous day's make are, in theory, removed and cannot collide
+#    with what 'svn update' needs to do.
 # ----------------------------------------------------------------------------
 dateTag=`date +%y%b%d`
 svnHost=svn.nersc.gov
@@ -317,6 +323,49 @@ checkAndHandleError "`nezero $pingWorks`" fatal "dropped packets to $svnHost"
 # check if this script itself has been changed 
 checkAndHandleError $scriptWasChanged warning "regressiontest_davinci was changed"
 
+# configure visit
+cd src
+rm -f config.log config.status config.cache config_log.txt make_log.txt
+#find . -name .svn -prune -false -o -name '*.so' -o -name '*.o' -o -name '*.d' -exec rm {} \;
+echo -e "LD_LIBRARY_PATH = $LD_LIBRARY_PATH" 1> config_log.txt 2>&1
+echo -e "Forcing LD_LIBRARY_PATH to /usr/local/lib" 1>> config_log.txt 2>&1
+LD_LIBRARY_PATH=/usr/local/lib
+export LD_LIBRARY_PATH
+./configure CXXFLAGS=-g MAKE=gmake --enable-parallel --enable-viewer-mesa-stub=no --enable-buildall 1>> config_log.txt 2>&1
+checkAndHandleError $? fatal "Pre-Update configure failed" config_log.txt 
+cd ..
+
+# test 'make clean' acts as expected
+cd data
+gmake clean 1> ../make_clean.out 2>&1
+cd ../src
+gmake clean 1>> ../make_clean.out 2>&1
+rm -f uncleaned_files_log.txt
+find . -name .svn -prune -false -o -name '*.so' -o -name '*.o' -o -name '*_moc.[Ch]' -o -name 'moc_*.[Ch]' 1> uncleaned_files_log.txt
+uncleanedFilesCount=`wc -l uncleaned_files_log.txt | tr -s ' ' | sed -e 's/^ //' | cut -d' ' -f1`
+checkAndHandleError $uncleanedFilesCount warning "Prior to svn update, make clean left files; removing manually" uncleaned_files_log.txt
+if test -n "$uncleanedFilesCount" -a $uncleanedFilesCount -ne 0; then
+    cat uncleaned_files_log.txt | tr -s ' ' | cut -d' ' -f2 | xargs -n 1 rm -f
+fi
+
+# test 'make distclean' acts as expected
+cd ../data
+gmake distclean 1> ../make_distclean.out 2>&1
+cd ../src
+make distclean 1>> ../make_distclean.out 2>&1
+rm -f undistcleaned_files_log.txt
+find . -name .svn -prune -false -o -name '*.d' -o -name '.depend' -o -name '.pardepend' 1> undistcleaned_files_log.txt
+# The 2nd find, below, finds only those Makefiles for which there is also
+# a coorsponding Makefile.in. 'make distclean' should have removed these
+# It also includes some special grep filtering for special cases of some
+# Makefiles that aren't easy for distclean to clean
+find . -name .svn -prune -false -o \( -name 'Makefile' -exec test -e \{\}.in \; \) -print | grep -v ./avt/Preprocessor/Makefile\\\|./tools/windowmaker/Makefile\\\|./tools/prep/Makefile\\\|./sim/examples/Makefile\\\|./common/siloobj/Makefile\\\|./common/siloobj_vtk_db/Makefile\\\|./cqscore/Makefile 1>> undistcleaned_files_log.txt
+undistcleanedFilesCount=`wc -l undistcleaned_files_log.txt | tr -s ' ' | sed -e 's/^ //' | cut -d' ' -f1`
+checkAndHandleError $undistcleanedFilesCount warning "Prior to svn update, make distclean left files; removing manually" undistcleaned_files_log.txt
+if test -n "$undistcleanedFilesCount" -a $undistcleanedFilesCount -ne 0; then
+    cat undistcleaned_files_log.txt | tr -s ' ' | cut -d' ' -f2 | xargs -n 1 rm -f
+fi
+
 # Update our current 'checkout' of visit trunk from NERSC
 pushd $rootTestDir 1> /dev/null 2>&1
 rm -f nersc_repo_update_$dateTag
@@ -367,52 +416,9 @@ fi
 conflictFiles=`grep '^C' nersc_repo_update_$dateTag | tr -s ' ' | cut -d' ' -f2`
 checkAndHandleError "`eqzero $conflictFiles`" fatal "conflicting files" "$conflictFiles"
 
-# build visit
-cd src
-rm -f config.log config.status config.cache config_log.txt make_log.txt
-#find . -name .svn -prune -false -o -name '*.so' -o -name '*.o' -o -name '*.d' -exec rm {} \;
-echo -e "LD_LIBRARY_PATH = $LD_LIBRARY_PATH" 1> config_log.txt 2>&1
-echo -e "Forcing LD_LIBRARY_PATH to /usr/local/lib" 1>> config_log.txt 2>&1
-LD_LIBRARY_PATH=/usr/local/lib
-export LD_LIBRARY_PATH
-./configure CXXFLAGS=-g MAKE=gmake --enable-parallel --enable-viewer-mesa-stub=no --enable-buildall 1>> config_log.txt 2>&1
-checkAndHandleError $? fatal "FIRST configure failed" config_log.txt 
-cd ..
-
-# test 'make clean' acts as expected
-cd data
-gmake clean 1> ../make_clean.out 2>&1
-cd ../src
-gmake clean 1>> ../make_clean.out 2>&1
-rm -f uncleaned_files_log.txt
-find . -name .svn -prune -false -o -name '*.so' -o -name '*.o' -o -name '*_moc.[Ch]' -o -name 'moc_*.[Ch]' 1> uncleaned_files_log.txt
-uncleanedFilesCount=`wc -l uncleaned_files_log.txt | tr -s ' ' | sed -e 's/^ //' | cut -d' ' -f1`
-checkAndHandleError $uncleanedFilesCount warning "make clean left files; removing manually" uncleaned_files_log.txt
-if test -n "$uncleanedFilesCount" -a $uncleanedFilesCount -ne 0; then
-    cat uncleaned_files_log.txt | tr -s ' ' | cut -d' ' -f2 | xargs -n 1 rm -f
-fi
-
-# test 'make distclean' acts as expected
-cd ../data
-gmake distclean 1> ../make_distclean.out 2>&1
-cd ../src
-make distclean 1>> ../make_distclean.out 2>&1
-rm -f undistcleaned_files_log.txt
-find . -name .svn -prune -false -o -name '*.d' -o -name '.depend' -o -name '.pardepend' 1> undistcleaned_files_log.txt
-# The 2nd find, below, finds only those Makefiles for which there is also
-# a coorsponding Makefile.in. 'make distclean' should have removed these
-# It also includes some special grep filtering for special cases of some
-# Makefiles that aren't easy for distclean to clean
-find . -name .svn -prune -false -o \( -name 'Makefile' -exec test -e \{\}.in \; \) -print | grep -v ./avt/Preprocessor/Makefile\\\|./tools/windowmaker/Makefile\\\|./tools/prep/Makefile\\\|./sim/examples/Makefile\\\|./common/siloobj/Makefile\\\|./common/siloobj_vtk_db/Makefile\\\|./cqscore/Makefile 1>> undistcleaned_files_log.txt
-undistcleanedFilesCount=`wc -l undistcleaned_files_log.txt | tr -s ' ' | sed -e 's/^ //' | cut -d' ' -f1`
-checkAndHandleError $undistcleanedFilesCount warning "make distclean left files; removing manually" undistcleaned_files_log.txt
-if test -n "$undistcleanedFilesCount" -a $undistcleanedFilesCount -ne 0; then
-    cat undistcleaned_files_log.txt | tr -s ' ' | cut -d' ' -f2 | xargs -n 1 rm -f
-fi
-
 # ok, now really go ahead and configure and build VisIt
 ./configure CXXFLAGS=-g MAKE=gmake --enable-parallel --enable-viewer-mesa-stub=no --enable-buildall 1>> config_log.txt 2>&1
-checkAndHandleError $? fatal "SECOND configure failed" config_log.txt 
+checkAndHandleError $? fatal "Post-Update configure failed" config_log.txt 
 gmake -j 6 1>> make_log.txt 2>&1
 checkAndHandleError $? fatal "gmake -j 6 failed in src" make_log.txt
 cd ..
