I went to add a no config option to the visit-install script and found that one already existed. It is invoked using "-c none". While looking at the code I found that there were several configurations that were not implemented with the "-c" option, so I added the missing ones. I also added a "-test" option that tests all 21 configurations. I also updated the help text since that was out of date. I added a blurb about the fix to the release notes. This resolves #1282.
git-svn-id: svn+ssh://edison.nersc.gov/project/projectdirs/visit/svn/visit/branches/2.7RC@22991 18c085ea-50e0-402c-830e-de6fd14e8384

diff --git a/src/svn_bin/visit-install b/src/svn_bin/visit-install
--- a/src/svn_bin/visit-install
+++ b/src/svn_bin/visit-install
@@ -348,6 +348,11 @@
 #
 #    Mark C. Miller, Wed Jan  8 11:25:02 PST 2014
 #    Made handling of 'data' directory conditional
+#
+#    Eric Brugger, Tue Mar 11 10:21:58 PDT 2014
+#    I added missing -c options and added a -test argument that tests
+#    all the -c options.
+#
 #-----------------------------------------------------------------------
 
 Compress=COMPRESS
@@ -361,6 +366,7 @@ group_ownership=none
 dir_permission=755
 file_permission=644
 dmg=false
+test=false
 
 # Figure out the platform so if we're on a platform for which we need to
 # perform extra steps, we know it.
@@ -406,6 +412,10 @@ while [ "$option_found" = "true" ]; do
          dmg=true
          shift
          ;;
+      -test)
+         test=true
+         shift
+         ;;
       *)
          option_found=false
          ;;
@@ -413,14 +423,16 @@ while [ "$option_found" = "true" ]; do
 done
 
 if [ "$#" != "3" ]; then
-   echo "Usage: visit-install [-c anag | anl | llnl_open | llnl_open_rz | llnl_open_cz | llnl_closed | nersc | ornl | princeton | sandia | sandia_closed | tacc | umich | nics | lsu | awe | clemson]"
-   echo "                     [-g group] [-b bank] [-gw] [-l] [-dmg]"
+   echo "Usage: visit-install [-c anag | anl | arl | asu | awe | clemson |"
+   echo "                         eth_zurich | llnl_open | llnl_open_rz |"
+   echo "                         llnl_open_cz | llnl_closed | lsu | nersc |"
+   echo "                         nics | ornl | princeton | sandia |"
+   echo "                         sandia_closed | tacc | umich]"
+   echo "                     [-g group] [-b bank] [-gw] [-l] [-dmg] [-test]"
    echo "                     [-beta | -private] version platform directory"
    echo ""
-   echo "                     This will install all of its files and"
-   echo "                     subdirectories directly in the specified"
-   echo "                     directory."
-   echo "                     (So use /usr/local/visit, not /usr/local)"
+   echo "This will install all of its files and subdirectories directly in"
+   echo "the specified directory. (So use /usr/local/visit, not /usr/local)"
    exit 1
 fi
 
@@ -520,32 +532,212 @@ else
    fi
 fi
 
+#
+# If the user specified test, then test all the config options.
+#
+if [ "$test" = "true" ]; then
+    echo "Testing none configuration..."
+    rm -rf $dir
+    $0 -c none $version $platform $dir > /dev/null 2>&1
+    files=`ls $dir/$version/.visit/hosts` 
+    if [ "$files" != "" ]; then
+       echo "failed"
+       exit 1
+    fi
+    echo "Testing anag configuration..."
+    rm -rf $dir
+    $0 -c anag $version $platform $dir > /dev/null 2>&1
+    files=`ls $dir/$version/bin/customlauncher` 
+    if [ "$files" == "" ]; then
+       echo "failed"
+       exit 1
+    fi
+    echo "Testing anl configuration..."
+    rm -rf $dir
+    $0 -c anl $version $platform $dir > /dev/null 2>&1
+    files=`ls $dir/$version/.visit/hosts/host_anl*` 
+    if [ "$files" == "" ]; then
+       echo "failed"
+       exit 1
+    fi
+    echo "Testing arl configuration..."
+    rm -rf $dir
+    $0 -c arl $version $platform $dir > /dev/null 2>&1
+    files=`ls $dir/$version/bin/customlauncher` 
+    if [ "$files" == "" ]; then
+       echo "failed"
+       exit 1
+    fi
+    echo "Testing asu configuration..."
+    rm -rf $dir
+    $0 -c asu $version $platform $dir > /dev/null 2>&1
+    files=`ls $dir/$version/bin/customlauncher` 
+    if [ "$files" == "" ]; then
+       echo "failed"
+       exit 1
+    fi
+    echo "Testing awe configuration..."
+    rm -rf $dir
+    $0 -c awe $version $platform $dir > /dev/null 2>&1
+    files=`ls $dir/$version/.visit/hosts/host_awe*` 
+    if [ "$files" == "" ]; then
+       echo "failed"
+       exit 1
+    fi
+    echo "Testing clemson configuration..."
+    rm -rf $dir
+    $0 -c clemson $version $platform $dir > /dev/null 2>&1
+    files=`ls $dir/$version/.visit/hosts/host_clemson*` 
+    if [ "$files" == "" ]; then
+       echo "failed"
+       exit 1
+    fi
+    echo "Testing eth_zurich configuration..."
+    rm -rf $dir
+    $0 -c eth_zurich $version $platform $dir > /dev/null 2>&1
+    files=`ls $dir/$version/bin/customlauncher` 
+    if [ "$files" == "" ]; then
+       echo "failed"
+       exit 1
+    fi
+    echo "Testing llnl_open configuration..."
+    rm -rf $dir
+    $0 -c llnl_open $version $platform $dir > /dev/null 2>&1
+    files=`ls $dir/$version/.visit/hosts/host_llnl_rzgw*` 
+    if [ "$files" == "" ]; then
+       echo "failed"
+       exit 1
+    fi
+    echo "Testing llnl_open_rz configuration..."
+    rm -rf $dir
+    $0 -c llnl_open_rz $version $platform $dir > /dev/null 2>&1
+    files=`ls $dir/$version/.visit/hosts/host_llnl_rz*` 
+    if [ "$files" == "" ]; then
+       echo "failed"
+       exit 1
+    fi
+    echo "Testing llnl_open_cz configuration..."
+    rm -rf $dir
+    $0 -c llnl_open_cz $version $platform $dir > /dev/null 2>&1
+    files=`ls $dir/$version/.visit/hosts/host_llnl*` 
+    if [ "$files" == "" ]; then
+       echo "failed"
+       exit 1
+    fi
+    echo "Testing llnl_closed configuration..."
+    rm -rf $dir
+    $0 -c llnl_closed $version $platform $dir > /dev/null 2>&1
+    files=`ls $dir/$version/.visit/hosts/host_llnl_closed*` 
+    if [ "$files" == "" ]; then
+       echo "failed"
+       exit 1
+    fi
+    echo "Testing lsu configuration..."
+    rm -rf $dir
+    $0 -c lsu $version $platform $dir > /dev/null 2>&1
+    files=`ls $dir/$version/.visit/hosts/host_lsu*` 
+    if [ "$files" == "" ]; then
+       echo "failed"
+       exit 1
+    fi
+    echo "Testing nersc configuration..."
+    rm -rf $dir
+    $0 -c nersc $version $platform $dir > /dev/null 2>&1
+    files=`ls $dir/$version/.visit/hosts/host_nersc*` 
+    if [ "$files" == "" ]; then
+       echo "failed"
+       exit 1
+    fi
+    echo "Testing nics configuration..."
+    rm -rf $dir
+    $0 -c nics $version $platform $dir > /dev/null 2>&1
+    files=`ls $dir/$version/.visit/hosts/host_nics*` 
+    if [ "$files" == "" ]; then
+       echo "failed"
+       exit 1
+    fi
+    echo "Testing ornl configuration..."
+    rm -rf $dir
+    $0 -c ornl $version $platform $dir > /dev/null 2>&1
+    files=`ls $dir/$version/.visit/hosts/host_ornl*` 
+    if [ "$files" == "" ]; then
+       echo "failed"
+       exit 1
+    fi
+    echo "Testing princeton configuration..."
+    rm -rf $dir
+    $0 -c princeton $version $platform $dir > /dev/null 2>&1
+    files=`ls $dir/$version/.visit/hosts/host_princeton*` 
+    if [ "$files" == "" ]; then
+       echo "failed"
+       exit 1
+    fi
+    echo "Testing sandia configuration..."
+    rm -rf $dir
+    $0 -c sandia $version $platform $dir > /dev/null 2>&1
+    files=`ls $dir/$version/.visit/hosts/host_sandia*` 
+    if [ "$files" == "" ]; then
+       echo "failed"
+       exit 1
+    fi
+    echo "Testing sandia_closed configuration..."
+    rm -rf $dir
+    $0 -c sandia_closed $version $platform $dir > /dev/null 2>&1
+    files=`ls $dir/$version/.visit/hosts/host_sandia_closed*` 
+    if [ "$files" == "" ]; then
+       echo "failed"
+       exit 1
+    fi
+    echo "Testing tacc configuration..."
+    rm -rf $dir
+    $0 -c tacc $version $platform $dir > /dev/null 2>&1
+    files=`ls $dir/$version/.visit/hosts/host_tacc*` 
+    if [ "$files" == "" ]; then
+       echo "failed"
+       exit 1
+    fi
+    echo "Testing umich configuration..."
+    rm -rf $dir
+    $0 -c umich $version $platform $dir > /dev/null 2>&1
+    files=`ls $dir/$version/.visit/hosts/host_umich*` 
+    if [ "$files" == "" ]; then
+       echo "failed"
+       exit 1
+    fi
+    exit 0
+fi
+
+#
+# If the user hasn't specified a config file, then prompt for one.
+#
 while [ "$config" = "prompt" ]; do
    echo "Choose a system configuration file.  A system configuration"
    echo "file contains profiles that make it easy to access VisIt on"
    echo "remote computers."
    echo ""
-   echo "   1) No system configuration"
-   echo "   2) Configuration for ANAG/APDEC collaborators."
-   echo "   3) ANL network"
-   echo "   4) LLNL open network (CZ and RZ)"
-   echo "   5)   LLNL open network (CZ only)"
-   echo "   6)   LLNL open network (RZ only)"
-   echo "   7) LLNL closed network"
-   echo "   8) NERSC network"
-   echo "   9) ORNL network"
-   echo "   10) Princeton network"
-   echo "   11) Sandia network"
-   echo "   12) Sandia closed network"
-   echo "   13) TACC network"
-   echo "   14) U of Michigan Center for Advanced Computing network"
+   echo "   1)  No system configuration"
+   echo "   2)  Configuration for ANAG/APDEC collaborators."
+   echo "   3)  ANL network"
+   echo "   4)  ARL network"
+   echo "   5)  ASU network"
+   echo "   6)  AWE network"
+   echo "   7)  Clemson University network"
+   echo "   8)  ETH Zurich network"
+   echo "   9)  LLNL open network (CZ and RZ)"
+   echo "   10)   LLNL open network (CZ only)"
+   echo "   11)   LLNL open network (RZ only)"
+   echo "   12) LLNL closed network"
+   echo "   13) Lousiana State University network"
+   echo "   14) NERSC network"
    echo "   15) NICS at University of Tennessee at Knoxville"
-   echo "   16) Lousiana State University network"
-   echo "   17) ETH Zurich"
-   echo "   18) AWE network"
-   echo "   19) Clemson University network"
+   echo "   16) ORNL network"
+   echo "   17) Princeton network"
+   echo "   18) Sandia network"
+   echo "   19) Sandia closed network"
+   echo "   20) TACC network"
+   echo "   21) U of Michigan Center for Advanced Computing network"
    echo ""
-   echo "Enter (1-18):"
+   echo "Enter (1-21):"
 
    read config
    case "$config" in
@@ -559,52 +751,58 @@ while [ "$config" = "prompt" ]; do
          config=anl
          ;;
       4)
-         config=llnl_open
+         config=arl
          ;;
       5)
-         config=llnl_open_cz
+         config=asu
          ;;
       6)
-         config=llnl_open_rz
+         config=awe
          ;;
       7)
-         config=llnl_closed
+         config=clemson
          ;;
       8)
-         config=nersc
+         config=eth_zurich
          ;;
       9)
-         config=ornl
+         config=llnl_open
          ;;
       10)
-         config=princeton
+         config=llnl_open_cz
          ;;
       11)
-         config=sandia
+         config=llnl_open_rz
          ;;
       12)
-         config=sandia_closed
+         config=llnl_closed
          ;;
       13)
-         config=tacc
+         config=lsu
          ;;
       14)
-         config=umich
+         config=nersc
          ;;
       15)
          config=nics
          ;;
       16)
-         config=lsu
+         config=ornl
          ;;
       17)
-         config=eth_zurich
+         config=princeton
          ;;
       18)
-         config=awe
+         config=sandia
          ;;
       19)
-         config=clemson
+         config=sandia_closed
+         ;;
+      20)
+         config=tacc
+         ;;
+      21)
+         config=umich
          ;;
       *)
          config=prompt
@@ -619,6 +817,16 @@ case "$config" in
       ;;
    anl)
       ;;
+   arl)
+      ;;
+   asu)
+      ;;
+   awe)
+      ;;
+   clemson)
+      ;;
+   eth_zurich)
+      ;;
    llnl_open)
       ;;
    llnl_open_cz)
@@ -627,8 +835,12 @@ case "$config" in
       ;;
    llnl_closed)
       ;;
+   lsu)
+      ;;
    nersc)
       ;;
+   nics)
+      ;; 
    ornl)
       ;;
    princeton)
@@ -641,20 +853,11 @@ case "$config" in
       ;;
    umich)
       ;;
-   nics)
-      ;; 
-   lsu)
-      ;;
-   eth_zurich)
-      ;;
-   awe)
-      ;;
-   clemson)
-      ;;
    *)
       echo "Illegal configuration option, choices are none, anag, anl,"
-      echo "llnl_open, llnl_open_cz, llnl_open_rz, llnl_closed, nersc, ornl, "
-      echo "princeton, sandia, sandia_closed, tacc, umich, nics, lsu, eth_zurich, awe, clemson."
+      echo "arl, asu, awe, clemson, eth_zurich, llnl_open, llnl_open_rz,"
+      echo "llnl_open_cz, llnl_closed, lsu, nersc, nics, ornl, princeton,"
+      echo "sandia, sandia_closed, tacc, umich"
       exit 4
       ;;
 esac
@@ -767,13 +970,26 @@ mkdir  "$dir"/$version+/.visit/hosts
 if [ "$config" = "anl" ]; then
    cp "$dir"/$version+/$platformDir/resources/hosts/$config/*.xml               "$dir"/$version+/.visit/hosts/
    cp "$dir"/$version+/$platformDir/resources/hosts/$config/customlauncher      "$dir"/$version+/bin/
-elif [ "$config" = "llnl_closed" ]; then
+elif [ "$config" = "arl" ]; then
+   cp "$dir"/$version+/$platformDir/resources/hosts/$config/customlauncher      "$dir"/$version+/bin/
+elif [ "$config" = "asu" ]; then
+   cp "$dir"/$version+/$platformDir/resources/hosts/$config/customlauncher      "$dir"/$version+/bin/
+elif [ "$config" = "awe" ]; then
    cp "$dir"/$version+/$platformDir/resources/hosts/$config/*.xml               "$dir"/$version+/.visit/hosts/
    cp "$dir"/$version+/$platformDir/resources/hosts/$config/customlauncher      "$dir"/$version+/bin/
-   cp "$dir"/$version+/$platformDir/resources/hosts/$config/config              "$dir"/$version+/.visit/
+elif [ "$config" = "clemson" ]; then
+   cp "$dir"/$version+/$platformDir/resources/hosts/$config/*.xml               "$dir"/$version+/.visit/hosts/
+   cp "$dir"/$version+/$platformDir/resources/hosts/$config/customlauncher      "$dir"/$version+/bin/
+elif [ "$config" = "eth_zurich" ]; then
+   cp "$dir"/$version+/$platformDir/resources/hosts/$config/customlauncher      "$dir"/$version+/bin/
 elif [ "$config" = "llnl_open" ]; then
    # Install both cz hosts and rzgw hosts. We're most likely in a client
    cp "$dir"/$version+/$platformDir/resources/hosts/llnl/*.xml                  "$dir"/$version+/.visit/hosts/
+   cp "$dir"/$version+/$platformDir/resources/hosts/llnl/customlauncher         "$dir"/$version+/bin/
+   cp "$dir"/$version+/$platformDir/resources/hosts/llnl/config                 "$dir"/$version+/.visit/
+elif [ "$config" = "llnl_open_rz" ]; then
+   # We're most likely installing on an rz machine.
+   cp "$dir"/$version+/$platformDir/resources/hosts/llnl_rz/*.xml               "$dir"/$version+/.visit/hosts/
    cp "$dir"/$version+/$platformDir/resources/hosts/llnl/customlauncher         "$dir"/$version+/bin/
    cp "$dir"/$version+/$platformDir/resources/hosts/llnl/config                 "$dir"/$version+/.visit/
 elif [ "$config" = "llnl_open_cz" ]; then
@@ -788,12 +1004,17 @@ elif [ "$config" = "llnl_open_cz" ]; then
 
    cp "$dir"/$version+/$platformDir/resources/hosts/llnl/customlauncher         "$dir"/$version+/bin/
    cp "$dir"/$version+/$platformDir/resources/hosts/llnl/config                 "$dir"/$version+/.visit/
-elif [ "$config" = "llnl_open_rz" ]; then
-   # We're most likely installing on an rz machine.
-   cp "$dir"/$version+/$platformDir/resources/hosts/llnl_rz/*.xml               "$dir"/$version+/.visit/hosts/
-   cp "$dir"/$version+/$platformDir/resources/hosts/llnl/customlauncher         "$dir"/$version+/bin/
-   cp "$dir"/$version+/$platformDir/resources/hosts/llnl/config                 "$dir"/$version+/.visit/
+elif [ "$config" = "llnl_closed" ]; then
+   cp "$dir"/$version+/$platformDir/resources/hosts/$config/*.xml               "$dir"/$version+/.visit/hosts/
+   cp "$dir"/$version+/$platformDir/resources/hosts/$config/customlauncher      "$dir"/$version+/bin/
+   cp "$dir"/$version+/$platformDir/resources/hosts/$config/config              "$dir"/$version+/.visit/
+elif [ "$config" = "lsu" ]; then
+   cp "$dir"/$version+/$platformDir/resources/hosts/$config/*.xml               "$dir"/$version+/.visit/hosts/
+   cp "$dir"/$version+/$platformDir/resources/hosts/$config/customlauncher      "$dir"/$version+/bin/
 elif [ "$config" = "nersc" ]; then
+   cp "$dir"/$version+/$platformDir/resources/hosts/$config/*.xml               "$dir"/$version+/.visit/hosts/
+   cp "$dir"/$version+/$platformDir/resources/hosts/$config/customlauncher      "$dir"/$version+/bin/
+elif [ "$config" = "nics" ]; then
    cp "$dir"/$version+/$platformDir/resources/hosts/$config/*.xml               "$dir"/$version+/.visit/hosts/
    cp "$dir"/$version+/$platformDir/resources/hosts/$config/customlauncher      "$dir"/$version+/bin/
 elif [ "$config" = "ornl" ]; then
@@ -814,25 +1035,11 @@ elif [ "$config" = "tacc" ]; then
    cp "$dir"/$version+/$platformDir/resources/hosts/$config/customlauncher      "$dir"/$version+/bin/
 elif [ "$config" = "umich" ]; then
    cp "$dir"/$version+/$platformDir/resources/hosts/$config/*.xml               "$dir"/$version+/.visit/hosts/
-elif [ "$config" = "nics" ]; then
-   cp "$dir"/$version+/$platformDir/resources/hosts/$config/*.xml               "$dir"/$version+/.visit/hosts/
-   cp "$dir"/$version+/$platformDir/resources/hosts/$config/customlauncher      "$dir"/$version+/bin/
 elif [ "$config" = "anag" ]; then
    cp "$dir"/$version+/$platformDir/resources/hosts/anag/config                 "$dir"/$version+/.visit/
    cp "$dir"/$version+/$platformDir/resources/hosts/anag/guiconfig              "$dir"/$version+/.visit/
    cp "$dir"/$version+/$platformDir/resources/hosts/anag/visitrc                "$dir"/$version+/.visit/
    cp "$dir"/$version+/$platformDir/resources/hosts/anag/customlauncher         "$dir"/$version+/bin/
-elif [ "$config" = "lsu" ]; then
-   cp "$dir"/$version+/$platformDir/resources/hosts/$config/*.xml               "$dir"/$version+/.visit/hosts/
-   cp "$dir"/$version+/$platformDir/resources/hosts/$config/customlauncher      "$dir"/$version+/bin/
-elif [ "$config" = "eth_zurich" ]; then
-   cp "$dir"/$version+/$platformDir/resources/hosts/$config/customlauncher      "$dir"/$version+/bin/
-elif [ "$config" = "awe" ]; then
-   cp "$dir"/$version+/$platformDir/resources/hosts/$config/*.xml               "$dir"/$version+/.visit/hosts/
-   cp "$dir"/$version+/$platformDir/resources/hosts/$config/customlauncher      "$dir"/$version+/bin/
-elif [ "$config" = "clemson" ]; then
-   cp "$dir"/$version+/$platformDir/resources/hosts/$config/*.xml               "$dir"/$version+/.visit/hosts/
-   cp "$dir"/$version+/$platformDir/resources/hosts/$config/customlauncher      "$dir"/$version+/bin/
 fi
 
 # Do the bank fixup
