merge cscs host profs from 2.7RC
git-svn-id: svn+ssh://edison.nersc.gov/project/projectdirs/visit/svn/visit/trunk@23392 18c085ea-50e0-402c-830e-de6fd14e8384

diff --git a/src/svn_bin/visit-install b/src/svn_bin/visit-install
--- a/src/svn_bin/visit-install
+++ b/src/svn_bin/visit-install
@@ -8,11 +8,13 @@
 # Date:   October 26, 1996
 #
 # Usage
-#    visit-install [-c anag | anl | llnl_open | llnl_open_rz | llnl_open_cz |
-#                      llnl_closed | nersc | ornl | princeton | sandia | 
-#                      tacc | umich | nics | lsu]
-#                  [-g group] [-gw] [-l] [-dmg] [-beta | -private]
-#                  version platform directory
+#    visit-install    [-c anag | anl | arl | asu | awe | clemson | cscs |"
+#                         eth_zurich | llnl_open | llnl_open_rz |"
+#                         llnl_open_cz | llnl_closed | lsu | nersc |"
+#                         nics | ornl | princeton | sandia |"
+#                         sandia_closed | tacc | umich]"
+#                      [-g group] [-b bank] [-gw] [-l] [-dmg] [-test]"
+#                      [-beta | -private] version platform directory"
 #
 #    The default is to install this version as the current version.
 #    The -beta flag makes this version the current beta version instead.
@@ -353,6 +355,8 @@
 #    I added missing -c options and added a -test argument that tests
 #    all the -c options.
 #
+#    Cyrus Harrison, Fri May 30 10:42:10 PDT 2014
+#    Added option for Swiss National Supercomputing Center (CSCS). 
 #-----------------------------------------------------------------------
 
 Compress=COMPRESS
@@ -423,7 +427,7 @@ while [ "$option_found" = "true" ]; do
 done
 
 if [ "$#" != "3" ]; then
-   echo "Usage: visit-install [-c anag | anl | arl | asu | awe | clemson |"
+   echo "Usage: visit-install [-c anag | anl | arl | asu | awe | clemson | cscs |"
    echo "                         eth_zurich | llnl_open | llnl_open_rz |"
    echo "                         llnl_open_cz | llnl_closed | lsu | nersc |"
    echo "                         nics | ornl | princeton | sandia |"
@@ -592,6 +596,14 @@ if [ "$test" = "true" ]; then
        echo "failed"
        exit 1
     fi
+    echo "Testing cscs configuration..."
+    rm -rf $dir
+    $0 -c cscs $version $platform $dir > /dev/null 2>&1
+    files=`ls $dir/$version/.visit/hosts/host_cscs*` 
+    if [ "$files" == "" ]; then
+       echo "failed"
+       exit 1
+    fi
     echo "Testing eth_zurich configuration..."
     rm -rf $dir
     $0 -c eth_zurich $version $platform $dir > /dev/null 2>&1
@@ -734,8 +746,9 @@ while [ "$config" = "prompt" ]; do
    echo "   17) Princeton network"
    echo "   18) Sandia network"
    echo "   19) Sandia closed network"
-   echo "   20) TACC network"
-   echo "   21) U of Michigan Center for Advanced Computing network"
+   echo "   20) Swiss National Supercomputing Center (CSCS) network"
+   echo "   22) TACC network"
+   echo "   22) U of Michigan Center for Advanced Computing network"
    echo ""
    echo "Enter (1-21):"
 
@@ -799,9 +812,12 @@ while [ "$config" = "prompt" ]; do
          config=sandia_closed
          ;;
       20)
-         config=tacc
+         config=cscs
          ;;
       21)
+         config=tacc
+         ;;
+      22)
          config=umich
          ;;
       *)
@@ -849,13 +865,15 @@ case "$config" in
       ;;
    sandia_closed)
       ;;
+   cscs)
+      ;;
    tacc)
       ;;
    umich)
       ;;
    *)
       echo "Illegal configuration option, choices are none, anag, anl,"
-      echo "arl, asu, awe, clemson, eth_zurich, llnl_open, llnl_open_rz,"
+      echo "arl, asu, awe, clemson, cscs, eth_zurich, llnl_open, llnl_open_rz,"
       echo "llnl_open_cz, llnl_closed, lsu, nersc, nics, ornl, princeton,"
       echo "sandia, sandia_closed, tacc, umich"
       exit 4
@@ -980,6 +998,8 @@ elif [ "$config" = "awe" ]; then
 elif [ "$config" = "clemson" ]; then
    cp "$dir"/$version+/$platformDir/resources/hosts/$config/*.xml               "$dir"/$version+/.visit/hosts/
    cp "$dir"/$version+/$platformDir/resources/hosts/$config/customlauncher      "$dir"/$version+/bin/
+elif [ "$config" = "cscs" ]; then
+   cp "$dir"/$version+/$platformDir/resources/hosts/$config/*.xml               "$dir"/$version+/.visit/hosts/
 elif [ "$config" = "eth_zurich" ]; then
    cp "$dir"/$version+/$platformDir/resources/hosts/$config/customlauncher      "$dir"/$version+/bin/
 elif [ "$config" = "llnl_open" ]; then
