minor fixes
git-svn-id: svn+ssh://edison.nersc.gov/project/projectdirs/visit/svn/visit/trunk@1975 18c085ea-50e0-402c-830e-de6fd14e8384

diff --git a/src/bin/visit_plugin b/src/bin/visit_plugin
--- a/src/bin/visit_plugin
+++ b/src/bin/visit_plugin
@@ -58,6 +58,13 @@
 #   Mark C. Miller, Wed Jun 20 18:06:14 PDT 2007
 #   Fixed comments in README regarding dependency files to remove explicit
 #   references to files named '.depend' or '.pardepend'
+#
+#   Mark C. Miller, Thu Sep  6 17:28:56 PDT 2007
+#   Changed all numeric tests to strings because I've found too often logic
+#   can fail with 'expected integer expression' error when using numeric
+#   comparisons (e.g. -eq -ne -lt -gt, etc.). Added logic to deal with
+#   possibility that xml2plugin may not be in path. Fixed up the instructions
+#   a bit. I added verbose message regarding email attempts.
 # ----------------------------------------------------------------------------
 #
 
@@ -98,7 +105,7 @@ if test -n "$commentSource"; then
     echo "" >> $1
 fi
 
-if test $testBuild -ne 0; then
+if test "$testBuild" != "0"; then
     if test -n "$testRun"; then
         echo "Prior to sending you this tarball, it was confirmed to build and" >> $1
         echo "run correctly with version $versionBuiltWith of VisIt." >> $1
@@ -112,30 +119,57 @@ fi
 
 cat >> $1 <<- EOF
 
-    Simple commands for installing and UNinstalling a plugin
-    (Works in most cases for VisIt versions 1.6 and newer)
+    Basic commands for installing and UNinstalling a plugin
     --------------------------------------------------------------
-    (Note: no '.tar.gz' after the plugin's name)
     To install...
-    % visit_plugin -install $pluginName 
+        % visit_plugin -install $pluginName 
     To UNinstall...
-    % visit_plugin -uninstall $pluginName
+        % visit_plugin -uninstall $pluginName
+
+    Note: There is no '.tar.gz' in the plugin's name
+
+    If the above commands fail, you may need to use this appraoch...
 
     Manual commands for installing and UNinstalling
-    (If the above commands fail, you can try this appraoch) 
     ----------------------------------------------------------------
-    % gunzip < $pluginName.tar.gz | tar xvf -
-    % cd $pluginName
+    To untar the plugin...
+        % gunzip < $pluginName.tar.gz | tar xvf -
     To install...
-    % xml2makefile -clobber $pluginName.xml
-    % make
+        % cd $pluginName
+        % xml2makefile -clobber $pluginName.xml
+        % make
     To UNinstall...
-    % make clean
+        % cd $pluginName
+        % make clean
 
     If you have problems, email mailto:visit-help@llnl.gov
 
-    Additional information to be aware of
-    -------------------------------------
+    The above commands should work in most cases. If both of the
+    above approaches fail, then read the material below to get 
+    more information regarding how VisIt's plugins work and how
+    to address any problems you may encounter.
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+    Additional information regarding VisIt database plugins... 
+    ----------------------------------------------------------------
     If you would like VisIt to test the plugin and automatically
     uninstall it if the test fails and the visit_plugin tool is 
     available in your installation, give the command
@@ -270,10 +304,20 @@ testBuildPluginTarball () {
     elif test -e .REQUIRED_VISIT_VERSION; then
         vers="-v `cat .REQUIRED_VISIT_VERSION`"
     fi
-    xml2makefile $vers -clobber $thePluginName.xml 1>/dev/null 2>&1
-    make -j 2 1>$oldDir/visit_plugin_${thePluginName}_make.log 2>&1
+    which xml2makefile 1>/dev/null 2>&1
+    if test "$?" = "0"; then
+        xml2makefile $vers -clobber $thePluginName.xml 1>/dev/null 2>&1
+    else
+        if test -e $scriptPath/xml2makefile; then
+            $scriptPath/xml2makefile $vers -clobber $thePluginName.xml 1>/dev/null 2>&1
+	else
+	    echo "Unable to find xml2makefile in your path or in ${scriptPath}"
+	    return
+	fi
+    fi
+    make 1>$oldDir/visit_plugin_${thePluginName}_make.log 2>&1
     hadError=$?
-    if test -z "$deleteIt" || test $deleteIt -ne 0; then
+    if test -z "$deleteIt" || test "$deleteIt" != "0"; then
         make clean 1>/dev/null 2>&1
         rm -rf $tmpDir/${theTarball}_tmp.$$
         echo $hadError
@@ -481,7 +525,7 @@ do
    esac
 done
 
-if test $optError -eq 0 && test -z "$action"; then
+if test "$optError" = "0" && test -z "$action"; then
     optError=1
     echo "************************************************"
     echo "************************************************"
@@ -490,7 +534,7 @@ if test $optError -eq 0 && test -z "$action"; then
     echo "************************************************"
 fi
 
-if test $optError -eq 0 && test -z "$pluginName"; then
+if test "$optError" = "0" && test -z "$pluginName"; then
     optError=1
     echo "************************"
     echo "************************"
@@ -500,7 +544,7 @@ if test $optError -eq 0 && test -z "$pluginName"; then
 fi
 
 if test "$optError" = "1"; then
-    echo "Usage:  $0 <options> [dirs]"
+    echo "Usage:  $0 <options> [plugin name]"
     echo "Available options:"
     echo "        -help             display this help message"
     echo "        -v  | -versions   quoted list of space separated version numbers(s)."
@@ -525,8 +569,17 @@ if test "$optError" = "1"; then
     echo "        <plugin name>     plugin name to process (e.g. SAMI or CGNS)."
     echo "                          If -p is specified, $0 will search for directories with"
     echo "                          the given name to package up. If -i is specified, $0 will"
-    echo "                          search for .tar.gz files with the given name."
+    echo "                          search for .tar.gz files with the given name. Should"
+    echo "                          always be last argument."
     exit 1
+fi
+
+#
+# Setup path to this script (and other visit tools) 
+#
+scriptPath="`dirname $0`"
+if test -n "`echo $path | grep $scriptPath`"; then
+    scriptPath=""
 fi
 
 #
@@ -560,7 +613,7 @@ if test $action = pack; then
             buildResult=`testBuildPluginTarball $pluginName.tar.gz 0`
             buildError=`echo $buildResult | cut -d' ' -f1`
             buildDir=`echo $buildResult | cut -d' ' -f2`
-            if test $buildError -ne 0; then
+            if test "$buildError" != "0"; then
                 echo "Test Build failed. Check visit_plugin_${pluginName}_make.log"
                 pushd $buildDir 1>/dev/null 2>&1
                 make clean 1>/dev/null 2>&1
@@ -571,7 +624,7 @@ if test $action = pack; then
                 echo "Passed"
                 echo -n "Now testing run..."
             fi
-            if test `testRunPluginTarball $buildDir` -ne 0; then
+            if test "`testRunPluginTarball $buildDir`" != "0"; then
                 echo "Test Run failed. Check debug logs copied to `pwd`."
                 pushd $buildDir 1>/dev/null 2>&1
                 make clean 1>/dev/null 2>&1
@@ -591,9 +644,9 @@ if test $action = pack; then
         #
         # Just test build it, if requested
         #
-        elif test $testBuild -ne 0; then
+        elif test "$testBuild" != "0"; then
             echo -n "Testing Build..."
-            if test `testBuildPluginTarball $pluginName.tar.gz` -ne 0; then
+            if test "`testBuildPluginTarball $pluginName.tar.gz`" != "0"; then
                 echo "Test Build failed"
                 exit 1
             fi
@@ -610,16 +663,21 @@ if test $action = pack; then
     # Mutt is unreliable. So, we loop making several attempts
     #
     if test -n "$emailRecipients"; then
+        which mutt 1>/dev/null 2>&1
+	if test "$?" != "0"; then
+	    echo "Unable to send mail because 'mutt' command is not in your path."
+	    exit 1
+	fi
         oldTmpDir=$TMPDIR
         TMPDIR=$tmpDir/mutt$$
 	export TMPDIR
 	mkdir $TMPDIR
 	chmod 700 $TMPDIR
         makeInstructionsFile mutt.msg 1>/dev/null 2>&1
-	muttAttempts=0
+	muttAttempts=1
 	while true; do
             env EMAIL="$meEmail" REPLYTO="$meEmail" mutt -s "Updated $pluginName plugin" -a $pluginName.tar.gz $emailRecipients < mutt.msg 1>$TMPDIR/mutt.errors 2>&1
-	    if test $? -ne 0; then
+	    if test "$?" != "0"; then
 	        sleep 1
 	    elif test -z "`cat $TMPDIR/mutt.errors`"; then
 	        cat $TMPDIR/mutt.errors
@@ -634,6 +692,9 @@ if test $action = pack; then
 		break;
 	    fi
 	done
+	if test $muttAttempts -le 10; then
+            echo "After $muttAttempts attempts, mutt successfully sent email to $emailRecipients"
+	fi
 	rm -rf $TMPDIR
 	TMPDIR=$oldTmpDir
 	export TMPDIR
@@ -644,7 +705,7 @@ if test $action = pack; then
     #
     # Delete tarball if we have no reason not to
     #
-    if test -n "$emailRecipients" && test $dontRemoveTarball -eq 0; then
+    if test -n "$emailRecipients" && test "$dontRemoveTarball" = "0"; then
         rm -f $tarballsToRemove
     fi
 
@@ -658,8 +719,9 @@ elif test $action = install; then
         buildResult=`testBuildPluginTarball $pluginName.tar.gz 0`
         buildError=`echo $buildResult | cut -d' ' -f1`
         buildDir=`echo $buildResult | cut -d' ' -f2`
-        if test $buildError -ne 0; then
-            echo "Failed. UNinstalling it"
+        if test "$buildError" != "0"; then
+            echo "Failed with result \"$buildResult\"."
+	    echo "UNinstalling it"
             pushd $buildDir 1>/dev/null 2>&1
             make clean 1>/dev/null 2>&1
             popd 1>/dev/null 2>&1
@@ -668,7 +730,7 @@ elif test $action = install; then
             echo "Succeeded."
             if test -n "$testRun" || test -e $buildDir/$pluginName/.TEST_RUN_COMMAND; then
 	        echo -n "Testing it..."
-                if test `testRunPluginTarball $buildDir/$pluginName` -ne 0; then
+                if test "`testRunPluginTarball $buildDir/$pluginName`" != "0"; then
                     echo "Failed."
 		    echo "Check debug logs copied to `pwd`."
 		    echo "Uninstalling it"
@@ -695,7 +757,7 @@ elif test $action = uninstall; then
     # Remove the plugin files from ~/.visit
     # 
     filesToRemove=`ls ~/.visit/*/plugins/databases/lib?${pluginName}* 2>/dev/null`
-    if test $? -ne 0 || test -z "$filesToRemove"; then
+    if test "$?" != "0" || test -z "$filesToRemove"; then
         echo "Unable to find any installed plugin files associated with \"$pluginName\""
         exit 1
     fi
@@ -707,7 +769,7 @@ elif test $action = uninstall; then
     read ans
     if test -n "$ans" && test $ans = yes; then
         rm -rf $filesToRemove
-        if test $? -ne 0; then
+        if test "$?" != "0"; then
             echo "Unable to remove the files"
             exit 1
         fi
