adding ITAPS database plugin writer; made configure smarter about silo library that is dependent on hdf5
git-svn-id: svn+ssh://edison.nersc.gov/project/projectdirs/visit/svn/visit/trunk@5717 18c085ea-50e0-402c-830e-de6fd14e8384

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -8619,6 +8619,16 @@ echo "${ECHO_T}no" >&6
 
 
 
+# Check for possible dependence on HDF5
+if test -n "$SILO_LIB"; then
+    if test -n "`strings $SILO_LIBFILE | grep -i 'SILO built with HDF5'`"; then
+        if test -z "`echo $SILO_LIB | tr ' ' '\n' | grep -x -e '-lhdf5'`"; then
+            { { echo "$as_me:$LINENO: error: Silo appears to have a dependence on HDF5. Add dependent libs after ':' in --with-silo arg." >&5
+echo "$as_me: error: Silo appears to have a dependence on HDF5. Add dependent libs after ':' in --with-silo arg." >&2;}
+   { (exit 1); exit 1; }; }
+        fi
+    fi
+fi
 
 
 # Check whether --with-exodus or --without-exodus was given.
