Add configure test for actual OSMesa offscreen window size limit, and use that instead of a hardcoded 4096.  Also, have build_visit do an additional patch to Mesa 6.4.2 to increase this limit from 4096 to 16384.
git-svn-id: svn+ssh://edison.nersc.gov/project/projectdirs/visit/svn/visit/trunk@4527 18c085ea-50e0-402c-830e-de6fd14e8384

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -2438,6 +2438,13 @@ fi
 
 
 
+#
+# IceT check.
+#
+
+
+
+
 
 # Check whether --enable-icet or --disable-icet was given.
 if test "${enable_icet+set}" = set; then
@@ -2474,10 +2481,10 @@ ax_ICET_LIB_STRATEGIES=
 if test "x$UseParallel" == "xno" -a "x$enable_icet" == "xyes" ; then
 	{ { echo "$as_me:$LINENO: error:
 IceT usage requested, but you're not doing a parallel build.  IceT requires
-\`--enable-parallel' to be specified." >&5
+'--enable-parallel' to be specified." >&5
 echo "$as_me: error:
 IceT usage requested, but you're not doing a parallel build.  IceT requires
-\`--enable-parallel' to be specified." >&2;}
+'--enable-parallel' to be specified." >&2;}
    { (exit 1); exit 1; }; }
 elif test "x$UseParallel" == "xyes" -a "x$enable_icet" == "xyes" ; then
 
@@ -5981,7 +5988,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5984:" \
+echo "$as_me:5991:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -8539,6 +8546,7 @@ have_libsiloh=no
 fi
 rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
+        rm -f junk.silo
 
 	if test "$have_libsiloh" = "yes"; then
             echo "$as_me:$LINENO: result: libsiloh5.a" >&5
@@ -8618,6 +8626,7 @@ silo_depends_on_hdf5=no
 fi
 rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
+        rm -f junk.silo
 
 	if test "$silo_depends_on_hdf5" = "yes"; then
             echo "$as_me:$LINENO: result: yes" >&5
@@ -9819,7 +9828,7 @@ ac_x_header_dirs='
 /usr/openwin/share/include'
 
 if test "$ac_x_includes" = no; then
-  # Guess where to find include files, by looking for Xlib.h.
+  # Guess where to find include files, by looking for Intrinsic.h.
   # First, try using that file with no special directory specified.
   cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
@@ -9827,7 +9836,7 @@ _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-#include <X11/Xlib.h>
+#include <X11/Intrinsic.h>
 _ACEOF
 if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
   (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
@@ -9854,7 +9863,7 @@ else
 sed 's/^/| /' conftest.$ac_ext >&5
 
   for ac_dir in $ac_x_header_dirs; do
-  if test -r "$ac_dir/X11/Xlib.h"; then
+  if test -r "$ac_dir/X11/Intrinsic.h"; then
     ac_x_includes=$ac_dir
     break
   fi
@@ -9868,18 +9877,18 @@ if test "$ac_x_libraries" = no; then
   # See if we find them without any special options.
   # Don't add to $LIBS permanently.
   ac_save_LIBS=$LIBS
-  LIBS="-lX11 $LIBS"
+  LIBS="-lXt $LIBS"
   cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-#include <X11/Xlib.h>
+#include <X11/Intrinsic.h>
 int
 main ()
 {
-XrmInitialize ()
+XtMalloc (0)
   ;
   return 0;
 }
@@ -10194,16 +10203,12 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-               HAVE_PTHREADS="Yes"
+  HAVE_PTHREADS="Yes"
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-               HAVE_PTHREADS="No"
+HAVE_PTHREADS="No"
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
@@ -10238,6 +10243,98 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
 fi
+
+
+
+
+#
+# Do a check to determine the actual limit of an OSMesa
+# window size.  Unfortunately, this must be done using
+# the C API and is thus a runtim check.
+#
+echo "$as_me:$LINENO: checking for OSMesa offscreen window size limit" >&5
+echo $ECHO_N "checking for OSMesa offscreen window size limit... $ECHO_C" >&6
+ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+oldcxxflags="$CXXFLAGS"
+oldldflags="$LDFLAGS"
+oldlibs="$LIBS"
+CXXFLAGS="-I$MESA/include"
+LDFLAGS="-L$MESA/lib -Wl,-rpath=$MESA/lib $LDFLAGS"
+LIBS="-lOSMesa -lMesaGL $GL_LIBS $X_LIBS $PTHREAD_LIB"
+OSMESA_SIZE_LIMIT="4096"
+if test "$cross_compiling" = yes; then
+  echo "$as_me:$LINENO: result: Cross-compiling... assuming $OSMESA_SIZE_LIMIT" >&5
+echo "${ECHO_T}Cross-compiling... assuming $OSMESA_SIZE_LIMIT" >&6
+
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+        #include <fstream>
+        #include <GL/osmesa.h>
+        using namespace std;
+        int main()
+        {
+            int w,h;
+            OSMesaGetIntegerv(OSMESA_MAX_WIDTH, &w);
+            OSMesaGetIntegerv(OSMESA_MAX_HEIGHT, &h);
+            ofstream out("junk.txt");
+            out << ((w < h) ? w : h) << endl;
+            out.close();
+            return 0;
+        }
+
+
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  OSMESA_SIZE_LIMIT=`cat junk.txt`
+        echo "$as_me:$LINENO: result: $OSMESA_SIZE_LIMIT" >&5
+echo "${ECHO_T}$OSMESA_SIZE_LIMIT" >&6
+
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+echo "$as_me:$LINENO: result: Test failed... assuming $OSMESA_SIZE_LIMIT" >&5
+echo "${ECHO_T}Test failed... assuming $OSMESA_SIZE_LIMIT" >&6
+
+fi
+rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+rm -f junk.txt
+cat >>confdefs.h <<_ACEOF
+#define OSMESA_SIZE_LIMIT $OSMESA_SIZE_LIMIT
+_ACEOF
+
+CXXFLAGS="$oldcxxflags"
+LDFLAGS="$oldldflags"
+LIBS="$oldlibs"
+ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
