Small cleanups.
* ac/icet.m4: try to use AS_IF, etc.
* aclocal.m4: regenerated
* configure: regenerated.

git-svn-id: svn+ssh://edison.nersc.gov/project/projectdirs/visit/svn/visit/trunk@5848 18c085ea-50e0-402c-830e-de6fd14e8384

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -5899,14 +5899,13 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
-
-        echo "$as_me:$LINENO: checking for strerror in -lcposix" >&5
-echo $ECHO_N "checking for strerror in -lcposix... $ECHO_C" >&6
-if test "${ac_cv_lib_cposix_strerror+set}" = set; then
+echo "$as_me:$LINENO: checking for library containing strerror" >&5
+echo $ECHO_N "checking for library containing strerror... $ECHO_C" >&6
+if test "${ac_cv_search_strerror+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lcposix  $LIBS"
+  ac_func_search_save_LIBS=$LIBS
+ac_cv_search_strerror=no
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -5951,24 +5950,80 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  ac_cv_lib_cposix_strerror=yes
+  ac_cv_search_strerror="none required"
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-ac_cv_lib_cposix_strerror=no
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_cposix_strerror" >&5
-echo "${ECHO_T}$ac_cv_lib_cposix_strerror" >&6
-if test $ac_cv_lib_cposix_strerror = yes; then
-  LIBS="$LIBS -lcposix"
-fi
+if test "$ac_cv_search_strerror" = no; then
+  for ac_lib in cposix; do
+    LIBS="-l$ac_lib  $ac_func_search_save_LIBS"
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
 
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char strerror ();
+int
+main ()
+{
+strerror ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_search_strerror="-l$ac_lib"
+break
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
 
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+  done
+fi
+LIBS=$ac_func_search_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_search_strerror" >&5
+echo "${ECHO_T}$ac_cv_search_strerror" >&6
+if test "$ac_cv_search_strerror" != no; then
+  test "$ac_cv_search_strerror" = "none required" || LIBS="$ac_cv_search_strerror $LIBS"
+
+fi
 
 
 BUILD_FORTRAN=""
@@ -10013,7 +10068,7 @@ ac_x_header_dirs='
 /usr/openwin/share/include'
 
 if test "$ac_x_includes" = no; then
-  # Guess where to find include files, by looking for Xlib.h.
+  # Guess where to find include files, by looking for Intrinsic.h.
   # First, try using that file with no special directory specified.
   cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
@@ -10021,7 +10076,7 @@ _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-#include <X11/Xlib.h>
+#include <X11/Intrinsic.h>
 _ACEOF
 if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
   (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
@@ -10048,7 +10103,7 @@ else
 sed 's/^/| /' conftest.$ac_ext >&5
 
   for ac_dir in $ac_x_header_dirs; do
-  if test -r "$ac_dir/X11/Xlib.h"; then
+  if test -r "$ac_dir/X11/Intrinsic.h"; then
     ac_x_includes=$ac_dir
     break
   fi
@@ -10062,18 +10117,18 @@ if test "$ac_x_libraries" = no; then
   # See if we find them without any special options.
   # Don't add to $LIBS permanently.
   ac_save_LIBS=$LIBS
-  LIBS="-lX11 $LIBS"
+  LIBS="-lXt $LIBS"
   cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-#include <X11/Xlib.h>
+#include <X11/Intrinsic.h>
 int
 main ()
 {
-XrmInitialize ()
+XtMalloc (0)
   ;
   return 0;
 }
@@ -10438,12 +10493,16 @@ if test "${enable_icet+set}" = set; then
   enableval="$enable_icet"
 
 fi;
-if [ "$DEFAULT_ICET_INCLUDE" == "" ] ; then
-   DEFAULT_ICET_INCLUDE="no"
+
+if test -z "${DEFAULT_ICET_INCLUDE}"; then
+  DEFAULT_ICET_INCLUDE="no"
 fi
-if [ "$DEFAULT_ICET_LIB" == "" ] ; then
-   DEFAULT_ICET_LIB="no"
+
+if test -z "${DEFAULT_ICET_LIB}"; then
+  DEFAULT_ICET_LIB="no"
 fi
+
+
 
 # Check whether --with-icet-includedir or --without-icet-includedir was given.
 if test "${with_icet_includedir+set}" = set; then
@@ -10463,23 +10522,32 @@ else
 
 fi;
 
-ICET_LIBS=
-ax_ICET_LIB=
-ax_ICET_LIB_MPI=
-ax_ICET_LIB_STRATEGIES=
 echo "$as_me:$LINENO: checking if IceT should be used" >&5
 echo $ECHO_N "checking if IceT should be used... $ECHO_C" >&6
-if test -n "${ICET_ENABLE}" ; then
-    enable_icet="yes"
+
+# Allow enabling IceT through a config site variable.
+if test -n "${ICET_ENABLE}" -o -n "${DEFAULT_ICET_INCLUDE}"; then
+  enable_icet="yes"
+else
+  enable_icet="no"
+
 fi
-if test -z "${enable_icet}" ; then
-   enable_icet="no"
-   if test -n "${DEFAULT_ICET_INCLUDE}" ; then
-      if [ "$UseParallel" == "yes" ] ; then
-         enable_icet="yes"
-      fi
-   fi
+
+
+# Check to make sure they aren't doing something weird.
+if test "x${enable_icet}" = "yes" -a \
+        \( -z "${UseParallel}" -o "x${UseParallel}" = "xno" \); then
+
+    { { echo "$as_me:$LINENO: error: IceT usage requested, but you're not doing a parallel
+build. IceT requires '--enable-parallel' to be specified." >&5
+echo "$as_me: error: IceT usage requested, but you're not doing a parallel
+build. IceT requires '--enable-parallel' to be specified." >&2;}
+   { (exit 1); exit 1; }; }
+
+
 fi
+
+
 echo "$as_me:$LINENO: result: $enable_icet" >&5
 echo "${ECHO_T}$enable_icet" >&6
 
@@ -10780,8 +10848,8 @@ fi
 
 
 
-        LDFLAGS=${ax_save_LDFLAGS}
-        CXXFLAGS=${ax_save_CXXFLAGS}
+        LDFLAGS="${ax_save_LDFLAGS}"
+        CXXFLAGS="${ax_save_CXXFLAGS}"
         ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
