Adding simulation support for OS X.
git-svn-id: svn+ssh://edison.nersc.gov/project/projectdirs/visit/svn/visit/trunk@2471 18c085ea-50e0-402c-830e-de6fd14e8384

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS TOPDIR PLATFORM_CPPFLAGS CXXFLAGS CXX LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT PARALLEL PARALLEL_CPPFLAGS MPI_LIBS MPI_CC MPI_CXX LIBSTATICPAR LIBSHAREDPAR LIBSHAREDPAR_UPDATEONLY PARDEP MESA_DIR MESA_INCLUDE MESA_LIBS VIEWER_MESA_STUB_CPPFLAGS VIEWER_MESA_LIBS BUILD_MESA_STUB CC CFLAGS ac_ct_CC GL_LIBS VTK_DIR VTK_INCLUDES VTK_LIBS VTK_LIGHTWEIGHT_LIBS AVTPREP_SER AVTPREP_PAR CONVERT_SER CONVERT_PAR MAKEMILI_SER MAKEMILI_PAR ENGINE_SER ENGINE_PAR ENGINELIBSER ENGINELIBPAR METADATA_SERVER MDSERVERLIB MDSERVEROBJ VISITPY SCRIPTINGLIB SCRIPTINGOBJ PY_BUILD_VISITMODULE GUI GUILIB GUIOBJ GUIFRAMEWORKS VIEWER VISWINDOW VIEWERLIB VIEWEROBJ VIEWERLIB_SRC VIEWEREXE_SRC ENGINEPROXYDIR ANNOTATION_FLAGS JAVAC JAVA_TARGET JAR JAVAFLAGS JAVAPLUGINFLAGS HELP PLOT_BUILD_DIRS OPERATOR_BUILD_DIRS DB_BUILD_DIRS BUILD_BZIP2 BZIP2_LIBS BUILD_GLEW GLEW_INCLUDE GLEW_LIBS BUILD_BILIB CXXCPP CPP F77 FFLAGS ac_ct_F77 SET_MAKE RANLIB ac_ct_RANLIB MAKEDEPEND BUILD_FORTRAN OS_RULE EGREP ZLIB_INCLUDE ZLIB_LIB SZIP SZIP_INCLUDE SZIP_LIB SZIP_LIBDIR HDF5 HDF5_INCLUDE HDF5_LIB HDF5_LIBDIR SILO_INCLUDE SILO_LIB SILO_LIBDIR EXODUS EXODUS_LIB EXODUS_LIBS EXODUS_FLAGS PDB PDB_FLAGS PDB_LIBS PDB_EXEC MILI MILI_FLAGS MILI_LIBS MILI_DIR HDF4 HDF4_FLAGS HDF4_LIBS HDF4_LIBDIR BOXLIB2D BOXLIB2D_INCLUDE BOXLIB2D_LIBS BOXLIB2D_LIBDIR BOXLIB3D BOXLIB3D_INCLUDE BOXLIB3D_LIBS BOXLIB3D_LIBDIR H5PART H5PART_INCLUDE H5PART_LIB H5PART_LIBDIR VISUS VISUS_INCLUDE VISUS_LIB NETCDF NETCDF_INCLUDE NETCDF_LIB NETCDF_CXX_LIB CGNS CGNS_INCLUDE CGNS_LIB GDAL GDAL_INCLUDE GDAL_LIB GDAL_LIBS CFITSIO CFITSIO_INCLUDE CFITSIO_LIB CFITSIO_LIBDIR ITAPS_C ITAPS_C_INCLUDE ITAPS_C_LIB ITAPS_S ITAPS_S_INCLUDE ITAPS_S_LIB ITAPS_INCLUDE ITAPS_LIB CREATE_ITAPS_LINK CCMIO CCMIO_INCLUDE CCMIO_LIBS CCMIO_LIBDIR SIMULATION ENGINE_CPPFLAGS SILOOBJVTK_CPPFLAGS PREPROCESSOR_CPPFLAGS PREPROCESSOR_PARALLEL_SRC COMPONENT_CPPFLAGS VISIT_VTK_CPPFLAGS VISIT_VTK_LDFLAGS VIEWER_CPPFLAGS QT_BIN QT_INCLUDE QT_LIB LIBQT QT_LIBS QUI_LIBS QT_LDFLAGS QT_STATICLDFLAGS QT_CXXFLAGS QT_MOC X_LIBS VTKQT_CPPFLAGS VTKQT VTKQT_LIBS PTHREAD_LIB PTHREAD_CXXFLAGS PYDIR PYVERSION PY_INCLUDEDIR PY_CXXFLAGS PY_LDFLAGS PY_LIB PY_CLI_LIB SHLIB_CREATEPROG SHLIB_LIBS SHLIB_SERLIBS SHLIB_PARLIBS SHLIB_MPI_LIBS SHLIB_ILIBS SHLIB_GLIBS SHLIB_VLIBS SHLIB_MLIBS SHLIB_ESERLIBS SHLIB_EPARLIBS SHLIB_SLIBS SHLIB_POSTPROCESS_ILIBS SHLIB_POSTPROCESS_GLIBS SHLIB_POSTPROCESS_VLIBS SHLIB_POSTPROCESS_MLIBS SHLIB_POSTPROCESS_ESERLIBS SHLIB_POSTPROCESS_EPARLIBS SHLIB_POSTPROCESS_SLIBS SHLIB_SOEXT SHLIB_LIBEXT SHLIB_POSTPROCESS SHLIB_POSTPROCESS_SER SHLIB_POSTPROCESS_PAR SHLIB_TMPDIR PREBIND_LIBS ENGINEWRAPSER ENGINEWRAPPAR CREATE_SILO_LINK CREATE_MILI_LINK CREATE_SZIP_LINK CREATE_HDF4_LINK CREATE_HDF5_LINK CREATE_NETCDF_LINK CREATE_CGNS_LINK CREATE_GDAL_LINK CREATE_EXODUS_LINK CREATE_BOXLIB2D_LINK CREATE_BOXLIB3D_LINK CREATE_CFITSIO_LINK CREATE_H5PART_LINK CREATE_CCMIO_LINK MG tmpbin tmpinc tmplib plotplugindir operatorplugindir databaseplugindir DATA_REL_VISIT_PATH LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS TOPDIR PLATFORM_CPPFLAGS CXXFLAGS CXX LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT PARALLEL PARALLEL_CPPFLAGS MPI_LIBS MPI_CC MPI_CXX LIBSTATICPAR LIBSHAREDPAR LIBSHAREDPAR_UPDATEONLY PARDEP MESA_DIR MESA_INCLUDE MESA_LIBS VIEWER_MESA_STUB_CPPFLAGS VIEWER_MESA_LIBS BUILD_MESA_STUB CC CFLAGS ac_ct_CC GL_LIBS VTK_DIR VTK_INCLUDES VTK_LIBS VTK_LIGHTWEIGHT_LIBS AVTPREP_SER AVTPREP_PAR CONVERT_SER CONVERT_PAR MAKEMILI_SER MAKEMILI_PAR ENGINE_SER ENGINE_PAR ENGINELIBSER ENGINELIBPAR METADATA_SERVER MDSERVERLIB MDSERVEROBJ VISITPY SCRIPTINGLIB SCRIPTINGOBJ PY_BUILD_VISITMODULE GUI GUILIB GUIOBJ GUIFRAMEWORKS VIEWER VISWINDOW VIEWERLIB VIEWEROBJ VIEWERLIB_SRC VIEWEREXE_SRC ENGINEPROXYDIR ANNOTATION_FLAGS JAVAC JAVA_TARGET JAR JAVAFLAGS JAVAPLUGINFLAGS HELP PLOT_BUILD_DIRS OPERATOR_BUILD_DIRS DB_BUILD_DIRS BUILD_BZIP2 BZIP2_LIBS BUILD_GLEW GLEW_INCLUDE GLEW_LIBS BUILD_BILIB CXXCPP CPP F77 FFLAGS ac_ct_F77 SET_MAKE RANLIB ac_ct_RANLIB MAKEDEPEND BUILD_FORTRAN OS_RULE EGREP ZLIB_INCLUDE ZLIB_LIB SZIP SZIP_INCLUDE SZIP_LIB SZIP_LIBDIR HDF5 HDF5_INCLUDE HDF5_LIB HDF5_LIBDIR SILO_INCLUDE SILO_LIB SILO_LIBDIR EXODUS EXODUS_LIB EXODUS_LIBS EXODUS_FLAGS PDB PDB_FLAGS PDB_LIBS PDB_EXEC MILI MILI_FLAGS MILI_LIBS MILI_DIR HDF4 HDF4_FLAGS HDF4_LIBS HDF4_LIBDIR BOXLIB2D BOXLIB2D_INCLUDE BOXLIB2D_LIBS BOXLIB2D_LIBDIR BOXLIB3D BOXLIB3D_INCLUDE BOXLIB3D_LIBS BOXLIB3D_LIBDIR H5PART H5PART_INCLUDE H5PART_LIB H5PART_LIBDIR VISUS VISUS_INCLUDE VISUS_LIB NETCDF NETCDF_INCLUDE NETCDF_LIB NETCDF_CXX_LIB CGNS CGNS_INCLUDE CGNS_LIB GDAL GDAL_INCLUDE GDAL_LIB GDAL_LIBS CFITSIO CFITSIO_INCLUDE CFITSIO_LIB CFITSIO_LIBDIR ITAPS_C ITAPS_C_INCLUDE ITAPS_C_LIB ITAPS_S ITAPS_S_INCLUDE ITAPS_S_LIB ITAPS_INCLUDE ITAPS_LIB CREATE_ITAPS_LINK CCMIO CCMIO_INCLUDE CCMIO_LIBS CCMIO_LIBDIR SIMULATION EXPORT_DYNAMIC ENGINE_CPPFLAGS SILOOBJVTK_CPPFLAGS PREPROCESSOR_CPPFLAGS PREPROCESSOR_PARALLEL_SRC COMPONENT_CPPFLAGS VISIT_VTK_CPPFLAGS VISIT_VTK_LDFLAGS VIEWER_CPPFLAGS QT_BIN QT_INCLUDE QT_LIB LIBQT QT_LIBS QUI_LIBS QT_LDFLAGS QT_STATICLDFLAGS QT_CXXFLAGS QT_MOC X_LIBS VTKQT_CPPFLAGS VTKQT VTKQT_LIBS PTHREAD_LIB PTHREAD_CXXFLAGS PYDIR PYVERSION PY_INCLUDEDIR PY_CXXFLAGS PY_LDFLAGS PY_LIB PY_CLI_LIB SHLIB_CREATEPROG SHLIB_LIBS SHLIB_SERLIBS SHLIB_PARLIBS SHLIB_MPI_LIBS SHLIB_ILIBS SHLIB_GLIBS SHLIB_VLIBS SHLIB_MLIBS SHLIB_ESERLIBS SHLIB_EPARLIBS SHLIB_SLIBS SHLIB_POSTPROCESS_ILIBS SHLIB_POSTPROCESS_GLIBS SHLIB_POSTPROCESS_VLIBS SHLIB_POSTPROCESS_MLIBS SHLIB_POSTPROCESS_ESERLIBS SHLIB_POSTPROCESS_EPARLIBS SHLIB_POSTPROCESS_SLIBS SHLIB_SOEXT SHLIB_LIBEXT SHLIB_POSTPROCESS SHLIB_POSTPROCESS_SER SHLIB_POSTPROCESS_PAR SHLIB_TMPDIR PREBIND_LIBS ENGINEWRAPSER ENGINEWRAPPAR CREATE_SILO_LINK CREATE_MILI_LINK CREATE_SZIP_LINK CREATE_HDF4_LINK CREATE_HDF5_LINK CREATE_NETCDF_LINK CREATE_CGNS_LINK CREATE_GDAL_LINK CREATE_EXODUS_LINK CREATE_BOXLIB2D_LINK CREATE_BOXLIB3D_LINK CREATE_CFITSIO_LINK CREATE_H5PART_LINK CREATE_CCMIO_LINK MG tmpbin tmpinc tmplib plotplugindir operatorplugindir databaseplugindir DATA_REL_VISIT_PATH LIBOBJS LTLIBOBJS'
 ac_subst_files='VARIABLES TARGETS DIRTARGETS LIBTARGETS PARLIBTARGETS SOURCE_DEPENDENCIES'
 
 # Initialize some variables set by options.
@@ -8852,14 +8852,68 @@ fi
 echo "$as_me:$LINENO: checking to see if simulation APIs should be enabled" >&5
 echo $ECHO_N "checking to see if simulation APIs should be enabled... $ECHO_C" >&6
 SIMULATION="$""(SIMULATION)"
-if test "$SHORT_UNAME" = "darwin" ; then
-   SIMULATION=""
-   echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-else
-   echo "$as_me:$LINENO: result: yes" >&5
+echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
+
+
+#
+# Determine if the linker support --export-dynamic
+#
+echo "$as_me:$LINENO: checking to see if --export-dynamic is supported" >&5
+echo $ECHO_N "checking to see if --export-dynamic is supported... $ECHO_C" >&6
+oldlflags="$LDFLAGS"
+EXPORT_DYNAMIC="-Wl,--export-dynamic"
+LDFLAGS="$EXPORT_DYNAMIC $LDFLAGS";
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+        EXPORT_DYNAMIC=""
 fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LDFLAGS="$oldldflags"
 
 
 #
@@ -10159,9 +10213,14 @@ done
 
 fi
 
+
 #
 # Figure out how to create shared libraries
 #
+# these defaults are tied to the case statement below and cannot be overriden
+SHLIB_POSTPROCESS="mv $""(LIBSHAREDTEMP) $""@"
+SHLIB_POSTPROCESS_SER="mv $""(LIBSHAREDTEMPSER) $""@"
+SHLIB_POSTPROCESS_PAR="mv $""(LIBSHAREDTEMPPAR) $""@"
 case $SHORT_UNAME in
   freebsd)
     # Expecting g++
@@ -10242,24 +10301,15 @@ case $SHORT_UNAME in
     fi
     if test -z "$SHLIB_SOEXT"; then SHLIB_SOEXT="dylib"; fi
     if test -z "$SHLIB_LIBEXT"; then SHLIB_LIBEXT="dylib"; fi
-    # Set the post processing step to something really useless because we
-    # don't need a postprocessing step since we're going to build directly
-    # in the lib directory.
-    SHLIB_POSTPROCESS="sleep 1"
-    SHLIB_POSTPROCESS_SER="sleep 1"
-    SHLIB_POSTPROCESS_PAR="sleep 1"
-
-    SHLIB_POSTPROCESS_ILIBS="sleep 1"
-    SHLIB_POSTPROCESS_GLIBS="sleep 1"
-    SHLIB_POSTPROCESS_SLIBS="sleep 1"
-    SHLIB_POSTPROCESS_VLIBS="sleep 1"
-    SHLIB_POSTPROCESS_MLIBS="sleep 1"
-    SHLIB_POSTPROCESS_ESERLIBS="sleep 1"
-    SHLIB_POSTPROCESS_EPARLIBS="sleep 1"
 
     # Set SHLIB_TMPDIR so that libraries are created directly in the lib directory.
     SHLIB_TMPDIR="$""(TOPDIR)/lib/"
+    # And now we don't need to move them anywhere.
+    SHLIB_POSTPROCESS=""
+    SHLIB_POSTPROCESS_SER=""
+    SHLIB_POSTPROCESS_PAR=""
     COMPATIBILITY_VERSION=`sed -e "s/b//" VERSION`
+
     # Set SHLIB_LIBS so the right libraries are added to the link line but also ensure
     # that the shared library is created with a unique starting address so we can
     # prebind.
@@ -10281,31 +10331,9 @@ case $SHORT_UNAME in
     PREBIND_LIBS="$""(PREBIND_LIBS) $""(GLEW_LIBS) $""(MESA_LIBS) -lvisit_vtk"
     ;;
 esac
-# Set up the defaults
-if test -z "$SHLIB_LIBS"           ; then SHLIB_LIBS=""; fi
-if test -z "$SHLIB_SERLIBS"        ; then SHLIB_SERLIBS=""; fi
-if test -z "$SHLIB_PARLIBS"        ; then SHLIB_PARLIBS=""; fi
-if test -z "$SHLIB_MPI_LIBS"       ; then SHLIB_MPI_LIBS=""; fi
-if test -z "$SHLIB_ILIBS"          ; then SHLIB_ILIBS=""; fi
-if test -z "$SHLIB_GLIBS"          ; then SHLIB_GLIBS=""; fi
-if test -z "$SHLIB_VLIBS"          ; then SHLIB_VLIBS=""; fi
-if test -z "$SHLIB_MLIBS"          ; then SHLIB_MLIBS=""; fi
-if test -z "$SHLIB_ESERLIBS"       ; then SHLIB_ESERLIBS=""; fi
-if test -z "$SHLIB_EPARLIBS"       ; then SHLIB_EPARLIBS=""; fi
-if test -z "$SHLIB_SLIBS"          ; then SHLIB_SLIBS=""; fi
-if test -z "$SHLIB_POSTPROCESS_ILIBS"    ; then SHLIB_POSTPROCESS_ILIBS="sleep 1"; fi
-if test -z "$SHLIB_POSTPROCESS_GLIBS"    ; then SHLIB_POSTPROCESS_GLIBS="sleep 1"; fi
-if test -z "$SHLIB_POSTPROCESS_VLIBS"    ; then SHLIB_POSTPROCESS_VLIBS="sleep 1"; fi
-if test -z "$SHLIB_POSTPROCESS_MLIBS"    ; then SHLIB_POSTPROCESS_MLIBS="sleep 1"; fi
-if test -z "$SHLIB_POSTPROCESS_ESERLIBS" ; then SHLIB_POSTPROCESS_ESERLIBS="sleep 1"; fi
-if test -z "$SHLIB_POSTPROCESS_EPARLIBS" ; then SHLIB_POSTPROCESS_EPARLIBS="sleep 1"; fi
-if test -z "$SHLIB_POSTPROCESS_SLIBS"    ; then SHLIB_POSTPROCESS_SLIBS="sleep 1"; fi
-if test -z "$SHLIB_SOEXT"          ; then SHLIB_SOEXT="so"; fi
-if test -z "$SHLIB_LIBEXT"         ; then SHLIB_LIBEXT="so"; fi
-if test -z "$SHLIB_POSTPROCESS"    ; then SHLIB_POSTPROCESS="mv $""(LIBSHAREDTEMP) $""@"; fi
-if test -z "$SHLIB_POSTPROCESS_SER"; then SHLIB_POSTPROCESS_SER="mv $""(LIBSHAREDTEMPSER) $""@"; fi
-if test -z "$SHLIB_POSTPROCESS_PAR"; then SHLIB_POSTPROCESS_PAR="mv $""(LIBSHAREDTEMPPAR) $""@"; fi
-if test -z "$PREBIND_LIBS"         ; then PREBIND_LIBS=""; fi
+# these might be overridden in a config-site file and thus must be set last
+if test -z "$SHLIB_SOEXT"  ; then SHLIB_SOEXT="so"; fi
+if test -z "$SHLIB_LIBEXT" ; then SHLIB_LIBEXT="so"; fi
 
 
 
@@ -18850,6 +18878,7 @@ s,@CCMIO_INCLUDE@,$CCMIO_INCLUDE,;t t
 s,@CCMIO_LIBS@,$CCMIO_LIBS,;t t
 s,@CCMIO_LIBDIR@,$CCMIO_LIBDIR,;t t
 s,@SIMULATION@,$SIMULATION,;t t
+s,@EXPORT_DYNAMIC@,$EXPORT_DYNAMIC,;t t
 s,@ENGINE_CPPFLAGS@,$ENGINE_CPPFLAGS,;t t
 s,@SILOOBJVTK_CPPFLAGS@,$SILOOBJVTK_CPPFLAGS,;t t
 s,@PREPROCESSOR_CPPFLAGS@,$PREPROCESSOR_CPPFLAGS,;t t
