svn co doesn't return 0
git-svn-id: svn+ssh://edison.nersc.gov/project/projectdirs/visit/svn/visit/trunk@1104 18c085ea-50e0-402c-830e-de6fd14e8384

diff --git a/src/clearcase_bin/build_visit b/src/clearcase_bin/build_visit
--- a/src/clearcase_bin/build_visit
+++ b/src/clearcase_bin/build_visit
@@ -621,10 +621,10 @@ function check_files
             else
                svn co --quite --non-interactive \
                   svn+ssh://$(whoami)@svn.nersc.gov/svn/visit/trunk/src
-               if [[ $? == 0 ]] ; then
-                   echo "Unable to build VisIt.  SVN download failed."
-                   return 1
-               fi
+#              if [[ $? == 0 ]] ; then
+#                  echo "Unable to build VisIt.  SVN download failed."
+#                  return 1
+#              fi
             fi
         else
             if [[ -e ${VISIT_FILE%.gz} || -e ${VISIT_FILE} ]] ; then
