Merge RC->2297 to trunk
git-svn-id: svn+ssh://edison.nersc.gov/project/projectdirs/visit/svn/visit/trunk@2299 18c085ea-50e0-402c-830e-de6fd14e8384

diff --git a/src/clearcase_bin/visit-bin-dist b/src/clearcase_bin/visit-bin-dist
--- a/src/clearcase_bin/visit-bin-dist
+++ b/src/clearcase_bin/visit-bin-dist
@@ -312,6 +312,9 @@
 #    Hank Childs, Thu Sep 20 22:09:43 PDT 2007
 #    Distribute visit_writer.so if it exists.
 #
+#    Hank Childs, Wed Oct 17 08:39:39 PDT 2007
+#    Improve existence test.  Also cut down on error messages from strip.
+#
 #------------------------------------------------------------------------------
 
 set DataFiles = "TRUE"
@@ -1032,15 +1035,18 @@ cp $VisItDir/lib/python/lib/$pyver/*.txt                $libdir/python/lib/$pyve
 cp $VisItDir/lib/python/lib/$pyver/*.py                 $libdir/python/lib/$pyver
 cp $VisItDir/lib/python/lib/$pyver/*.pyc                $libdir/python/lib/$pyver
 cp $VisItDir/lib/python/lib/$pyver/*.pyo                $libdir/python/lib/$pyver
-if(-e "$VisItDir/lib/python/lib/$pyver/*.$SHLIB_SOEXT") then
+ls $VisItDir/lib/python/lib/$pyver/*.$SHLIB_SOEXT >& /dev/null
+if ($? == 0) then
   cp $VisItDir/lib/python/lib/$pyver/*.$SHLIB_SOEXT     $libdir/python/lib/$pyver
 endif
 cp $VisItDir/lib/python/lib/$pyver/config/*             $libdir/python/lib/$pyver/config
 cp $VisItDir/lib/python/lib/$pyver/lib-dynload/*        $libdir/python/lib/$pyver/lib-dynload
-if(-e "$VisItDir/lib/python/lib/$pyver/site-packages/PIL.*") then
+ls $VisItDir/lib/python/lib/$pyver/site-packages/PIL.* >& /dev/null
+if ($? == 0) then
   cp $VisItDir/lib/python/lib/$pyver/site-packages/PIL.* $libdir/python/lib/$pyver/site-packages
 endif
-if(-e "$VisItDir/lib/python/lib/$pyver/site-packages/PIL/*") then
+ls $VisItDir/lib/python/lib/$pyver/site-packages/PIL/* >& /dev/null
+if ($? == 0) then
   cp $VisItDir/lib/python/lib/$pyver/site-packages/PIL/*  $libdir/python/lib/$pyver/site-packages/PIL
 endif
 cp $VisItDir/lib/python/lib/$pyver/xml/*.{py,pyc,pyo}         $libdir/python/lib/$pyver/xml
@@ -1113,7 +1119,8 @@ cp $VisItDir/include/visit/[A-M]*.h             $incdir/visit
 cp $VisItDir/include/visit/[N-Q]*.h             $incdir/visit
 cp $VisItDir/include/visit/[R-Z]*.h             $incdir/visit
 cp $VisItDir/include/visit/a[a-uw-zA-Z]*.h      $incdir/visit
-if(-e "$VisItDir/include/visit/av[a-su-zA-Z]*.h") then
+ls $VisItDir/include/visit/av[a-su-zA-Z]*.h >& /dev/null
+if ($? == 0) then
   cp $VisItDir/include/visit/av[a-su-zA-Z]*.h   $incdir/visit
 endif
 cp $VisItDir/include/visit/avt[a-z]*.h          $incdir/visit
@@ -1122,65 +1129,81 @@ cp $VisItDir/include/visit/avt[N-Z]*.h          $incdir/visit
 cp $VisItDir/include/visit/[b-z]*.h             $incdir/visit
 cp $VisItDir/include/mesa/GL/*.h                $incdir/mesa/GL
 cp $VisItDir/include/vtk/*.h                    $incdir/vtk
-if(-e "$VisItDir/include/vtk/*.txx") then
+ls $VisItDir/include/vtk/*.txx >& /dev/null
+if ($? == 0) then
   cp $VisItDir/include/vtk/*.txx                $incdir/vtk
 endif
-if(-e "$VisItDir/include/vtk/Common/[a-uw-zA-Z]*.h") then
+ls $VisItDir/include/vtk/Common/[a-uw-zA-Z]*.h >& /dev/null
+if ($? == 0) then
   cp $VisItDir/include/vtk/Common/[a-uw-zA-Z]*.h   $incdir/visit
 endif
-if(-e "$VisItDir/include/vtk/Common/[a-uw-zA-Z]*.txx") then
+ls $VisItDir/include/vtk/Common/[a-uw-zA-Z]*.txx >& /dev/null
+if ($? == 0) then
   cp $VisItDir/include/vtk/Common/[a-uw-zA-Z]*.txx $incdir/visit
 endif
-if(-e "$VisItDir/include/vtk/Common/v[a-su-zA-Z]*.h") then
+ls $VisItDir/include/vtk/Common/v[a-su-zA-Z]*.h >& /dev/null
+if ($? == 0) then
   cp $VisItDir/include/vtk/Common/v[a-su-zA-Z]*.h  $incdir/visit
 endif
-if(-e "$VisItDir/include/vtk/Common/v[a-su-zA-Z]*.txx") then
+ls $VisItDir/include/vtk/Common/v[a-su-zA-Z]*.txx >& /dev/null
+if ($? == 0) then
   cp $VisItDir/include/vtk/Common/v[a-su-zA-Z]*.txx $incdir/visit
 endif
-if(-e "$VisItDir/include/vtk/Common/vt[a-jl-zA-Z]*.h") then
+ls $VisItDir/include/vtk/Common/vt[a-jl-zA-Z]*.h >& /dev/null
+if ($? == 0) then
   cp $VisItDir/include/vtk/Common/vt[a-jl-zA-Z]*.h $incdir/vtk/Common
 endif
-if(-e "$VisItDir/include/vtk/Common/vt[a-jl-zA-Z]*.txx") then
+ls $VisItDir/include/vtk/Common/vt[a-jl-zA-Z]*.txx >& /dev/null
+if ($? == 0) then
   cp $VisItDir/include/vtk/Common/vt[a-jl-zA-Z]*.txx $incdir/vtk/Common
 endif
 cp $VisItDir/include/vtk/Common/vtk[a-zA-J]*.h   $incdir/vtk/Common
 cp $VisItDir/include/vtk/Common/vtk[a-zA-J]*.txx $incdir/vtk/Common
 cp $VisItDir/include/vtk/Common/vtk[K-Z_]*.h      $incdir/vtk/Common
-if(-e "$VisItDir/include/vtk/Common/vtk[K-Z]*.txx") then
+ls $VisItDir/include/vtk/Common/vtk[K-Z]*.txx >& /dev/null
+if ($? == 0) then
   cp $VisItDir/include/vtk/Common/vtk[K-Z]*.txx $incdir/vtk/Common
 endif
 cp $VisItDir/include/vtk/Filtering/*.h          $incdir/vtk/Filtering
 cp $VisItDir/include/vtk/Filtering/*.txx        $incdir/vtk/Filtering
 cp $VisItDir/include/vtk/GenericFiltering/*.h   $incdir/vtk/GenericFiltering
-if(-e "$VisItDir/include/vtk/GenericFiltering/*.txx") then
+ls $VisItDir/include/vtk/GenericFiltering/*.txx >& /dev/null
+if ($? == 0) then
   cp $VisItDir/include/vtk/GenericFiltering/*.txx $incdir/vtk/GenericFiltering
 endif
 cp $VisItDir/include/vtk/Graphics/*.h           $incdir/vtk/Graphics
-if(-e "$VisItDir/include/vtk/Graphics/*.txx") then
+ls $VisItDir/include/vtk/Graphics/*.txx >& /dev/null
+if ($? == 0) then
   cp $VisItDir/include/vtk/Graphics/*.txx       $incdir/vtk/Graphics
 endif
 cp $VisItDir/include/vtk/Hybrid/*.h             $incdir/vtk/Hybrid
-if(-e "$VisItDir/include/vtk/Hybrid/*.txx") then
+ls $VisItDir/include/vtk/Hybrid/*.txx >& /dev/null
+if ($? == 0) then
   cp $VisItDir/include/vtk/Hybrid/*.txx         $incdir/vtk/Hybrid
 endif
 cp $VisItDir/include/vtk/IO/*.h                 $incdir/vtk/IO
-if(-e "$VisItDir/include/vtk/IO/*.txx") then
+ls $VisItDir/include/vtk/IO/*.txx >& /dev/null
+if ($? == 0) then
   cp $VisItDir/include/vtk/IO/*.txx             $incdir/vtk/IO
 endif
 cp $VisItDir/include/vtk/Imaging/*.h            $incdir/vtk/Imaging
-if(-e "$VisItDir/include/vtk/Imaging/*.txx") then
+ls $VisItDir/include/vtk/Imaging/*.txx >& /dev/null
+if ($? == 0) then
   cp $VisItDir/include/vtk/Imaging/*.txx        $incdir/vtk/Imaging
 endif
 cp $VisItDir/include/vtk/MangleMesaInclude/*.h  $incdir/vtk/MangleMesaInclude
-if(-e "$VisItDir/include/vtk/MangleMesaInclude/*.txx") then
+ls $VisItDir/include/vtk/MangleMesaInclude/*.txx >& /dev/null
+if ($? == 0) then
   cp $VisItDir/include/vtk/MangleMesaInclude/*.txx $incdir/vtk/MangleMesaInclude
 endif
 cp $VisItDir/include/vtk/Rendering/*.h          $incdir/vtk/Rendering
-if(-e "$VisItDir/include/vtk/Rendering/*.txx") then
+ls $VisItDir/include/vtk/Rendering/*.txx >& /dev/null
+if ($? == 0) then
   cp $VisItDir/include/vtk/Rendering/*.txx      $incdir/vtk/Rendering
 endif
 cp $VisItDir/include/vtk/Utilities/*.h          $incdir/vtk/Utilities
-if(-e "$VisItDir/include/vtk/Utilities/*.txx") then
+ls $VisItDir/include/vtk/Utilities/*.txx >& /dev/null
+if ($? == 0) then
   cp $VisItDir/include/vtk/Utilities/*.txx      $incdir/vtk/Utilities
 endif
 cp $VisItDir/include/vtk/Utilities/vtkexpat/*.h $incdir/vtk/Utilities/vtkexpat
@@ -1205,22 +1228,27 @@ cp $VisItDir/include/qt/private/*.h             $incdir/qt/private
 if (-e $VisItDir/help) then
    echo "Copying help files to the distribution..."
    cp $VisItDir/help/[a-gi-z]*.html    $helpdir
-   if(-e "$VisItDir/help/h[a-df-z]*.html") then
+   ls $VisItDir/help/h[a-df-z]*.html >& /dev/null
+   if ($? == 0) then
      cp $VisItDir/help/h[a-df-z]*.html $helpdir
    endif
-   if(-e "$VisItDir/help/he[a-km-z]*.html") then
+   ls $VisItDir/help/he[a-km-z]*.html >& /dev/null
+   if ($? == 0) then
      cp $VisItDir/help/he[a-km-z]*.html $helpdir
    endif
-   if(-e "$VisItDir/help/hel[a-oq-z]*.html") then
+   ls $VisItDir/help/hel[a-oq-z]*.html >& /dev/null
+   if ($? == 0) then
      cp $VisItDir/help/hel[a-oq-z]*.html $helpdir
    endif
-   if(-e "$VisItDir/help/help[a-z]*.html") then
+   ls $VisItDir/help/help[a-z]*.html >& /dev/null
+   if ($? == 0) then
      cp $VisItDir/help/help[a-z]*.html $helpdir
    endif
    cp $VisItDir/help/help0[01]*.html   $helpdir
    cp $VisItDir/help/help0[23]*.html   $helpdir
    cp $VisItDir/help/help0[45]*.html   $helpdir
-   if(-e "$VisItDir/help/help0[67]*.html") then
+   ls "$VisItDir/help/help0[67]*.html" >& /dev/null
+   if ($? == 0) then
      cp $VisItDir/help/help0[67]*.html $helpdir
    endif
    if (-e $VisItDir/help/visit.helpml) then
@@ -1268,11 +1296,11 @@ if ($Strip == "TRUE") then
     if("$os" == "darwin") then
         echo "We don't do library stripping on MacOS X."
     else
-        strip $bindir/*
-        strip $libdir/*
-        strip $plugindir/plots/*
-        strip $plugindir/operators/*
-        strip $plugindir/databases/*
+        strip $bindir/* >& /dev/null
+        strip $libdir/* >& /dev/null
+        strip $plugindir/plots/* >& /dev/null
+        strip $plugindir/operators/* >& /dev/null
+        strip $plugindir/databases/* >& /dev/null
     endif
 endif
 
