fix indentation

diff --git a/.github/workflows/check_methoddoc_gen.yaml b/.github/workflows/check_methoddoc_gen.yaml
--- a/.github/workflows/check_methoddoc_gen.yaml
+++ b/.github/workflows/check_methoddoc_gen.yaml
@@ -14,48 +14,48 @@ jobs:
     steps:
 
     - name: Set up Python
-       uses: actions/setup-python@v2
-       with:
-         python-version: '3.9'
+      uses: actions/setup-python@v2
+      with:
+        python-version: '3.9'
   
     - name: Checkout code
-       uses: actions/checkout@v2
+      uses: actions/checkout@v2
 
     - name: Get Changed Files (for PRs)
-       id: changed-files
-       uses: tj-actions/changed-files@v42
-       with:
-         separator: ' '
+      id: changed-files
+      uses: tj-actions/changed-files@v42
+      with:
+        separator: ' '
 
     - name: Check synced files
-       run: |
-          have_func_rst=0
-          have_methdoc_c=0
-          for f in ${{ steps.changed-files.outputs.all_changed_files }}; do
-              if [[ "$f" == "src/doc/python_script/functions.rst" ]]; then
-                  have_func_rst=1
-              elif [[ "$f" == "src/visitpy/common/MethodDoc.C" ]]; then
-                  have_methdoc_c=1
-              fi
-          done
-          if [[ $have_func_rst -ne 0 ]]; then
-              if [[ $have_methdoc_c -eq 0 ]]; then
-                  echo "Error: Changes to functions.rst require regeneration of MethodDoc.C (and possibly MethodDoc.h)"
-                  echo "       Please follow https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/dev_manual/UpdatingPythonDocStrings.html"
-                  exit 1
-              fi
+      run: |
+        have_func_rst=0
+        have_methdoc_c=0
+        for f in ${{ steps.changed-files.outputs.all_changed_files }}; do
+          if [[ "$f" == "src/doc/python_script/functions.rst" ]]; then
+            have_func_rst=1
+          elif [[ "$f" == "src/visitpy/common/MethodDoc.C" ]]; then
+            have_methdoc_c=1
           fi
-          if [[ $have_methdoc_c -ne 0 ]]; then
-              if [[ $have_func_rst -eq 0 ]]; then
-                  echo "Error: You have made changes directly to a *generated* file, MethodDoc.C."
-                  echo "       You must make your changes to functions.rst and regenerate MethodDoc.C (and possibly MethodDoc.h)."
-                  echo "       Please follow https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/dev_manual/UpdatingPythonDocStrings.html"
-                  exit 1
-              fi
+        done
+        if [[ $have_func_rst -ne 0 ]]; then
+          if [[ $have_methdoc_c -eq 0 ]]; then
+             echo "Error: Changes to functions.rst require regeneration of MethodDoc.C (and possibly MethodDoc.h)"
+             echo "       Please follow https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/dev_manual/UpdatingPythonDocStrings.html"
+             exit 1
           fi
+        fi
+        if [[ $have_methdoc_c -ne 0 ]]; then
+          if [[ $have_func_rst -eq 0 ]]; then
+             echo "Error: You have made changes directly to a *generated* file, MethodDoc.C."
+             echo "       You must make your changes to functions.rst and regenerate MethodDoc.C (and possibly MethodDoc.h)."
+             echo "       Please follow https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/dev_manual/UpdatingPythonDocStrings.html"
+             exit 1
+          fi
+        fi
 
     - name: Check Generated MethodDoc.C
-       run: |
+      run: |
          cp src/visitpy/common/MethodDoc.C src/visitpy/common/MethodDoc.C.orig
          pushd src/doc
          ./functions_to_plain_py.py
